### PR TITLE
Don't use obvious directions at ramp bifurcations

### LINKED ISSUE #4895: Missing instruction at a ramp bifurcation
At ramp bifurcations OSRM suppresses obvious instructions 
http://map.project-osrm.org/?z=18&center=33.645919%2C-84.444394&loc=33.645961%2C-84.443981&loc=33.646068%2C-84.445086&hl=en&alt=0
screenshot from 2018-02-19 10-02-21

Valhalla does not suppress turn instructions in similar case and produces for the above route  [ `Keep right to take I 85 South toward I 285/Montgomery.`](https://valhalla.github.io/demos/routing/index.html#loc=18,33.646053,-84.444542&locations=[{%22lat%22:33.646018730864775,%22lon%22:-84.4440883398056},{%22lat%22:33.64609911436225,%22lon%22:-84.44499492645264}]&costing=%22auto%22) instruction due to condition [`maneuver.ramp() && prev_edge->IsRampUse()`](https://github.com/valhalla/valhalla/blob/69e1d050a6f0845cb0ad58c9ba401cb1fdacf68d/src/odin/maneuversbuilder.cc#L1570)

In order to synchronize guidance instructions OSRM should handle a case of ramp bifurcations as non-obvious. The current OSRM ramp bifurcations implementation is captured by the feature tests:
- [Kreuz Oranienburg](https://github.com/Project-OSRM/osrm-backend/blob/a8bc2cf8a78c1831b259701ad66ce575c7f5768a/features/guidance/anticipate-lanes.feature#L136)
- [Fork on motorway links - don't fork on through](https://github.com/Project-OSRM/osrm-backend/blob/a8bc2cf8a78c1831b259701ad66ce575c7f5768a/features/guidance/fork.feature#L369)
- [Fork on motorway links - don't fork on through but use lane](features/guidance/turn-lanes.feature:860)

/cc @srividyacb @dgearhart

### PR DESCRIPTION
**Pull request by oxidase**
# Issue

Fixes #4895 as
screenshot from 2018-02-19 12-00-50

"before-after" comparison in SF-area http://bl.ocks.org/d/1f6b51ce1cafff2463d913cd05d40f73 

## Tasklist

 - [x] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [x] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md)
 - [x] review
 - [x] adjust for comments
 - [ ] cherry pick to release branch

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by chaupow** [comment]
Codewise it looks good to me! 👍  

I just wonder about this scenario:
```
Given the node map
    """
         /-----------c
    a---b------------d
    """

And the ways
    | nodes | highway       | name | destination |
    | ab    | motorway      |      |             |
    | bc    | motorway_link |      | City 17     |
    | bd    | motorway_link |      | Ravenholm   |
```
If `ab` is not a ramp:
1. Does this scenario exist? 🤔 
2. Should it also be handled the same?

I am thinking about this scenario:
https://www.mapillary.com/app/?lat=49.86228055555556&lng=8.598833333333333&z=17&pKey=hb7H7YDWiRMYbnzio1dv6A&x=0.6825900002246823&y=0.5478995910837546&zoom=1&focus=photo

The signs show a straight vs a exit right, but there are 4 lanes, two go straight, two go to the right - so it is somehow a weird mix of a fork / exit?

Routing this way A5 -> A67:

http://map.project-osrm.org/?z=15&center=49.857215%2C8.602273&loc=49.871102%2C8.600750&loc=49.848803%2C8.596029&hl=en&alt=0

does not have an instruction (even though there is a name change)

Routing this way A5 -> A5:

http://map.project-osrm.org/?z=15&center=49.857215%2C8.602273&loc=49.871102%2C8.600750&loc=49.850325%2C8.608990&hl=en&alt=0

has an instruction (even though there is no name change).


Maybe this should another issue - and this is not osrm _code_ related but more a guidance question?

**Comment by oxidase** [comment]
>     Does this scenario exist? thinking
No, i have added an intersection from a motorway to two ramps  to the feature test.

>    Should it also be handled the same?

Yes, atm such intersections are handled in [`motorway_handler`](https://github.com/Project-OSRM/osrm-backend/blob/a8bc2cf8a78c1831b259701ad66ce575c7f5768a/src/guidance/motorway_handler.cpp#L191) as forks (related issue #3106). PR makes both cases consistent:   in `motorway_handler` and `turn_handler` will be used `assignFork` for intersections  with motorway links.

A5 -> A5 or A67 case is a usual motorway intersection and handled in [`motorway_handler`](https://github.com/Project-OSRM/osrm-backend/blob/a8bc2cf8a78c1831b259701ad66ce575c7f5768a/src/guidance/motorway_handler.cpp#L256-L293). An "obvious" instruction for `A5 -> A67` is `{type = NewName (1), direction_modifier = Straight (4)}`, so it is suppressed later in the guidance post-processing.

**Comment by dgearhart** [comment]
@oxidase for a fork - typically, I would see `ab` as a `motorway_link` too 

@chaupow For the A5 -> A67 case: I believe this is a bug, it should call out a `Continue on A67` since it is a motorway to [motorway](https://www.openstreetmap.org/way/1711296) transition and the user needs to know to continue straight onto A67.


@chaupow For the A5 -> A67 case: Since the edge is a [motorway_link](https://www.openstreetmap.org/way/1711292#map=17/49.85869/8.59790) - it should be called out as a right exit so the user knows to take the exit even though the name remains the same. This scenario happens in the US too.

**Comment by dgearhart** [comment]
@oxidase :+1: LGTM thanks

**Comment by chaupow** [comment]
I'll be giving a 👍 here - @oxidase you might wanna figure out whether there should be an issue for the case I highlighted or not :)

**Pull request merged**
