### PR TITLE
Do not compile Coordinate sources directly into the OSRM library

### PR DESCRIPTION
**Pull request by m-kuhn**
It is already included in the COORDINATES "OBJECT" target to which the OSRM
library is linked.
This fixes the possibility to build OSRM as a shared library.

### CODE REVIEW

**Comment by TheMarex** [comment]
Looks good.  Only concern is the additional build target for travis. Does travis recycle the build artefacts from the debug build?

**Comment by DennisOSRM** [comment]
Travis most probably does not cache any artifacts. Happy to merge this pull request if the new target is build in Release mode.

@m-kuhn Can you add a commit to test Release build only for the shared library?

**Comment by m-kuhn** [comment]
Done.
Not sure if I need to specify a separate port for the new target?

**Comment by DennisOSRM** [comment]
Thanks. for the quick commit. Just move it to port 5020.

**Comment by TheMarex** [comment]
@m-kuhn Could you rebase on develop so we can see if travis likes to compile it this time :construction_worker:

**Comment by m-kuhn** [comment]
@m-kuhn loves pull request feedbacks where the major part of the time to fulfill the wish is spent on opening a terminal.

**Comment by DennisOSRM** [comment]
One detail @m-kuhn:

could you move the port of the third test environment to 5020, so we can execute the tests in parallel on the same host.

**Comment by DennisOSRM** [comment]
Thanks again. I merged manually and took the liberty to change the third port to 5020.

**Comment by m-kuhn** [comment]
Great, thanks @DennisOSRM 
The port was an open question, good you felt free to just do it.

**Pull request merged**
