### PR TITLE
Removed STXXL support.

### PR DESCRIPTION
**Pull request by akashihi**
#5759 

As discussed on a mailing list, stxxl is abandonware and not used with osrm in the wild anymore.

## Tasklist

 - [X] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [X] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [X] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md)
 - [ ] review
 - [ ] adjust for comments
 - [ ] cherry pick to release branch

### CODE REVIEW

**Comment by mloskot** [comment]
Linking the list thread for the archive https://lists.openstreetmap.org/pipermail/osrm-talk/2020-June/001863.html

**Comment by mloskot** [comment]
@daniel-j-h & @TheMarex Forgive me bothering you directly, but do you see a chance for review of this PR?

**Comment by daniel-j-h** [comment]
cc @danpat

**Comment by mloskot** [comment]
Any prospect of reviewing this?

**Review by gardster — APPROVED** [review]

**Pull request merged**
