### PR TITLE
Make MMapMemoryAllocator map files in read-only (O_RDONLY) mode

### PR DESCRIPTION
**Pull request by slavanap**
Mapping with O_RDWR will cause copy_up across Docker layers.

# Issue

https://github.com/Project-OSRM/osrm-backend/issues/5820

## Tasklist

 - [ ] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))

### CODE REVIEW

**Review by akashihi — APPROVED** [review]

**Comment by akashihi** [comment]
@slavanap Could you please fix formatting (by calling scripts/format.sh)?

**Comment by slavanap** [comment]
@akashihi done + rewritten the commit

**Comment by slavanap** [comment]
I don't know what to write to CHANGELOG.md file re this commit. Would appreciate any suggestion even if it would be to write nothing.

**Comment by slavanap** [comment]
// rebased to new `master`

**Comment by akashihi** [comment]
No idea what to write to CHANGELOG, lets just merge it :)

**Pull request merged**
