### PR TITLE
added lua binding for osmium::Way::id()

### PR DESCRIPTION
**Pull request by bjtaylor1**
as discussed here: https://github.com/Project-OSRM/osrm-backend/issues/1369

### CODE REVIEW

**Comment by DennisOSRM** [comment]
Thanks for the PR. I'm going to merge this manually into develop branch.

**Comment by emiltin** [comment]
is this ready to merge?

**Comment by DennisOSRM** [comment]
Already cherry-picked into develop branch.

**Comment by DennisOSRM** [comment]
It's here: https://github.com/Project-OSRM/osrm-backend/commit/d77a88c21e6b847c02b2d52af0ee7519c634a851

**Comment by emiltin** [comment]
did the syntax change? when i try:

```lua
id_plus_one = 1 + way.id
```

i get:

```
attempt to concatenate field 'id' (a function value)
```

**Comment by emiltin** [comment]
way.id() doesn't work either i get:

terminate called after throwing an instance of 'osrm::exception'
  what():  ERROR occured in profile script:
No matching overload found, candidates:
long id(Way const&)
Aborted (core dumped)
*** Exited with code 134.

**Comment by DennisOSRM** [comment]
reopening to track whats missing in this issue

**Comment by DennisOSRM** [comment]
shouldn't it be `way:id()` rather than `way.id()`

**Comment by TheMarex** [comment]
So, this does actually work with ```way:id()``` right? Can we close?

**Comment by DennisOSRM** [comment]
There was an issue binding members from a superclass into Lua. It does not yet work.

**Comment by bjtaylor1** [comment]
The binding I added has to be used like `way:id()` in lua. It worked ok when I did it....

**Comment by TheMarex** [comment]
Uhm, adding this to profile.lua
```lua
  local id_test = way:id() + 1
  io.write("id: ", id_test, "\n")
```
Has exactly the indented effect. So it does work, doesn't it? Can we close @DennisOSRM?

**Comment by DennisOSRM** [comment]
Hmm.. perhaps my notebook is not up to date. I'll revisit tomorrow morning and update/close the issue as needed.

**Comment by kemets** [comment]
Is it possible that this is no longer working? Using `way:id()` I get a `std::runtime_error: 'Trying to use unregistered class'` . The following minimal `profile.lua` demonstrates the problem:

    function node_function(node)
      return 1
    end

    function way_function (way)
      local id_test = way:id() + 1
      io.write("id: ", id_test, "\n")
      return 1
    end

I am using OSRM on Mac OS X with the dependencies installed using homebrew.

**Comment by emiltin** [comment]
not sure if it's the reason for your error, but the node and way functions take two arguments:
https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L213

**Comment by kemets** [comment]
You're correct, but it doesn't seem to matter. I started from https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua , but the example I gave in this thread was based on https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/examples/postgis.lua#L48 which only takes one argument for the node and way functions. I adapted my example to take two arguments, but the error remains.

**Comment by systemed** [comment]
Same `'Trying to use unregistered class'` error for me (also OS X, Homebrew).

**Comment by kemets** [comment]
Sorry for the late follow up.  The exception is caused by the return type of the `id()` function defined for `osmium::OSMObject` (i.e., the parent class for all derived classes such as `osmium::Way` and `osmium::Node`). 

Looking at the definition of `osmium::OSMObject::id()`:

    /// Get ID of this object.
    object_id_type id() const noexcept {
        return m_id;
    }

The `object_id_type` is a typedef for `int64_t`:

    typedef int64_t  object_id_type;

The definition of `int64_t` depends on the platform. On Ubuntu Trusty (where we the exception is not thrown) it is defined in `/usr/include/stdint.h`:

    # if __WORDSIZE == 64
    typedef long int                int64_t;
    # else
    __extension__
    typedef long long int           int64_t;

However, the definition on OS X is in `/usr/include/sys/_types/_int64_t.h`:

    typedef long long               int64_t;

which seems to be the cause of the exception. 

We're deploying on Linux so switched our development environment to a virtual machine to circumvent this problem. Not sure where this should be solved, I expect at the luabind side?

**Comment by TheMarex** [comment]
@kemets so you are running on a 32 bit system? Your systems standard library headers should define `int64_t` correctly as 64bit integer. Is it a bug in luabind on OSX?

**Comment by kemets** [comment]
Both my OS X 10.9.5 and Ubuntu Trusty are 64 bit. Did a quick test also:

    sizeof(long int): 8
    sizeof(long long): 8
    sizeof(long long int): 8
    sizeof(int64_t): 8

Might it have something to do with the `LUABIND_NUMBER_CONVERTER` definitions in https://github.com/luabind/luabind/blob/master/luabind/detail/policy.hpp#L690 ?

**Comment by TheMarex** [comment]
@kemets oh yeah type deduction will most likely not figure out that `long long int` == `long int`. Did you try it with adding `int64_t` to the list?

**Comment by daniel-j-h** [comment]
As reported today on IRC, `way::id()` still crashes OSRM. User reported this for Ubuntu.

**Comment by TheMarex** [comment]
@daniel-j-h you mean `way:id()` ? Is this a luabind version thing?

**Comment by daniel-j-h** [comment]
Yes, sorry for the typo.

On OSX @danpat reported the following exception being thrown:

    /usr/local/include/luabind/detail/make_instance.hpp
    80:        throw std::runtime_error("Trying to use unregistered class");

On IRC (Ubuntu, Release build) a user reported:

    [info]   vehicle
    terminate called after throwing an instance of 'osrm::util::exception'
    terminate called recursively
    terminate called recursively
    Aborted (core dumped)

which looks like a throwing destructor to me (bad). Could actually be the same issue.

**Comment by TheMarex** [comment]
@daniel-j-h Can't reproduce this on Arch Linux with the following profile modification:

```
diff --git a/profiles/car.lua b/profiles/car.lua
index f6bfd23..2adcabd 100644
--- a/profiles/car.lua
+++ b/profiles/car.lua
@@ -212,6 +212,7 @@ function node_function (node, result)
 end
 
 function way_function (way, result)
+  io.write("id:" .. way:id())
   local highway = way:get_value_by_key("highway")
   local route = way:get_value_by_key("route")
   local bridge = way:get_value_by_key("bridge")
```

Can the user try this and report the error?

**Pull request merged**
