### PR TITLE
[not ready] Use Boost where it provides low overhead features

### PR DESCRIPTION
**Pull request by daniel-j-h**
This Pull Request tracks the progress. Do not merge yet.

Detailed descriptions are in the commit messages, please make sure to read them for discussion.

The basic idea is to rip out hand-written features that have a more or less 1:1 feature parity with plain Boost. From a quick glance sometimes our hand-written code provides less (which can make sense to speed up compilation). The main problem is they are not as thoroughly tested and do not have the level of assertions that Boost provides.

We should make sure to include only what we need, e.g. `<boost/range/irange.hpp>` instead of `<boost/range.hpp>` and keep an eye on compilation times.

This means also removing features we use from Boost which we can use from C++11 / C++14, while testing for portability issues.

### CODE REVIEW

**Comment by daniel-j-h** [comment]
After half an hour travis complained about the `irange` switch at https://github.com/Project-OSRM/osrm-backend/commit/f3d6b8ae98f844cc31648c4f2e1a0b5fe0c0083d. Seems like the cucumber tests are failing in large quantity. From a quick glance over the commit, I'm unsure why. Have to investigate this.

**Comment by daniel-j-h** [comment]
Snippet comparing both versions: http://coliru.stacked-crooked.com/a/4a9317c65dcf00b8

**Comment by daniel-j-h** [comment]
The only difference I can come up with is the following edge case:

    irange(x, y);

where `x > y`: http://coliru.stacked-crooked.com/a/4eba09b985445e5e

In this case, Boost's `irange` (rightfully) triggers an assert while our implementation directly jumps into its `operator!=` where it returns `false` instead, signalling the end iterator.

This should be checked at call site and not in `irange`. There might be issues in the code using it, since it silently returns an empty range in those edge cases.

/cc @TheMarex if you have the time to take a look (not important)

**Comment by daniel-j-h** [comment]
Update to the irange issue:

```c++
auto r = boost::irange<unsigned int>(0, 15);
std::cout << r.size() << std::endl;
```

results in `-4294967281` on my Boost 1.55, on recent Boost versions this seems to be fixed:

http://coliru.stacked-crooked.com/a/8d0093d1191d022f

The problem seems to be the `integer_range`s `difference_type`, which is `long int`.

**Comment by TheMarex** [comment]
Ah yeah I remember that problem now. Ran into that a few times, I guess that is why we switched.

**Comment by daniel-j-h** [comment]
@TheMarex Gnaa could have saved me a couple of hours of pain and suffering there :P reverting, but then also adding some asserts on negative sized ranges and so on.

**Comment by danpat** [comment]
How often do we run the test suite through a debug build that will actually have asserts enabled?  If we wanted to be thorough, we'd have Travis do both a Release and Debug build, and test both and publish the Release build if both worked.

**Comment by daniel-j-h** [comment]
@danpat this is something I'd like to do in combination with https://github.com/Project-OSRM/osrm-backend/issues/1601.
That's additional high load for the CI though.

**Comment by daniel-j-h** [comment]
@TheMarex okay if I merge this? Want to get the queue of pull requests down.

One issue that is scoped to this branch but tracked in https://github.com/Project-OSRM/osrm-backend/issues/1692#issuecomment-142971706: if I get the okay to switch in `Boost.Variant`, I could rip out `third_party/variant` completely. If that's too much for now, I'm totally fine with merging this branch as-is.

**Comment by TheMarex** [comment]
@daniel-j-h Just leave `mapbox/variant`. We need to investigate more if removing it makes sense. The variant type is part of the hot code paths and as such requires an in-depth look before we can do significant changes.

**Comment by daniel-j-h** [comment]
> Otherwise this is good to merge after a rebase.

Meh, this wasn't good after a merge. At least some build configurations seem to fail, indicating undefined behavior or worse. Investigating right now in hotfix https://github.com/Project-OSRM/osrm-backend/pull/1712. I should have cought it earlier :/

**Pull request merged**
