### PR TITLE
upgrade to cucumber 2.0

### PR DESCRIPTION
**Pull request by emiltin**
Upgrades to cucumber 2.0.
Remember to run 'bundle' upgrade cucumber and related gems.
Tested with ruby 2.1.5p273 and 2.2.0p0, all tests passing.

- [ ] test with ruby 1.9
- [ ] test with ruby 2.2
- [ ] check if travis and appveyor can use ruby 2.2, if yes then we could require ruby 2.2 in the Gemfile to avoid incompatibilities with older ruby versions
- [ ] make sure CIs pass all tests

### CODE REVIEW

**Comment by emiltin** [comment]
Travis seems to be using outdated code?
Some tests fails with references to files like features/testbot/matching.feature, which does not exist in the repo, as can be verified here: https://github.com/Project-OSRM/osrm-backend/tree/fix/cucumber2.0/features/testbot.

**Comment by TheMarex** [comment]
Huh? What branch did you base this on? Its present in `develop` https://github.com/Project-OSRM/osrm-backend/blob/develop/features/testbot/matching.feature

**Comment by emiltin** [comment]
let me check what happened

**Comment by emiltin** [comment]
must have worked from an outdated develop branch. should be fixed now.

**Comment by TheMarex** [comment]
:+1: works for me on Arch as well.

**Comment by alex85k** [comment]
Cucumber 2.0 + Ruby 1.9.3 32 bit + Windows = OK after minimal patching mentoned in PR

**Comment by alex85k** [comment]
Ruby 2,2 32bit + Windows = multiple gherkin wanings https://github.com/cucumber/gherkin/issues/273 + 2 failing tests related to UTF8
most likely, this is he problem of RubyInstaller, not testing scripts

**Pull request merged**
