### PR TITLE
Build osmium_convert in order to be able to eventually replace osmosis

### PR DESCRIPTION
**Pull request by daniel-j-h**
This provides a script to build the libosmium examples such as
osmium_convert (to convert from xml to pbf).

I initially tried a CMake ExternalProject setup, but this was more
complicated than I initially thought; this is the more elegant solution.

The goal is to eventually rip out osmosis, so that we no longer depend
on java for the cucumber tests.

To be done, adapt:

- [x] Cucumber tests
- [x] Dockerfile
- [x] Travis CI
- [x] Wiki

References:

- https://github.com/Project-OSRM/osrm-backend/issues/1788

### CODE REVIEW

**Comment by daniel-j-h** [comment]
@emiltin after invoking this script we now have `./osmium/examples/osmium_convert`. I tested the following hack to use osmium_convert instead of osmosis:

```diff
diff --git a/features/support/data.rb b/features/support/data.rb
index 62ed7d3..e16b1ec 100644
--- a/features/support/data.rb
+++ b/features/support/data.rb
@@ -233,8 +233,8 @@ def convert_osm_to_pbf
   unless File.exist?("#{osm_file}.osm.pbf")
     log_preprocess_info
     log "== Converting #{osm_file}.osm to protobuffer format...", :preprocess
-    unless system "osmosis --read-xml #{osm_file}.osm --write-pbf #{osm_file}.osm.pbf omitmetadata=true >>#{PREPROCESS_LOG_FILE} 2>&1"
-      raise OsmosisError.new $?, "osmosis exited with code #{$?.exitstatus}"
+    unless system "../build/osmium/examples/osmium_convert --from-format=xml #{osm_file}.osm --to-format=pbf #{osm_file}.osm.pbf >>#{PREPROCESS_LOG_FILE} 2>&1"
+      raise OsmosisError.new $?, "osmium_convert exited with code #{$?.exitstatus}"
     end
     log '', :preprocess
   end
```

With this all cucumber scenarios pass! :tada:

Is this the idiomatic way to do it (especially re. relative paths)?
What else needs to be done, except for integrating this and renaming OsmosisError?

**Comment by daniel-j-h** [comment]
It looks like the Rakefile also uses osmosis to crop osm data by means of extracting a bounding box.

**Comment by daniel-j-h** [comment]
@emiltin why do we need to convert from xml to pbf in the first place? @joto just brought it up to me that osrm-backend is able to read osm xml files with libosmium. If the conversion is done only for readability, than we could drop it altogether.

**Comment by TheMarex** [comment]
@daniel-j-h hm. Yes since `libosmium` now wrapps it I feel okay with dropping this to use the most minimal way to support this.

**Comment by emiltin** [comment]
looks good. might want to rename OsmosisError to something more telling though.

the reason for handling both osm (xml) and pbf in cucumber is simply to tests both ways of importing data. most tests use osm. see features/testbot/protobuffer.feature.

**Comment by daniel-j-h** [comment]
@emiltin would like to switch to using pbf only and then simply no longer convert from xml to pbf, eliminating the need for osmosis. We don't want to test the xml or pbf parsing, that is libosmium's scope.

**Comment by emiltin** [comment]
OK that will simply a few things. It will not result in any significant speedup though, since it's only a few out of all tests that currently use pbf.

**Comment by daniel-j-h** [comment]
Waiting for Travis then we're free of osmosis / java.

**Comment by emiltin** [comment]
you might want to remove the cucumber tests that deal with pbf as well

**Comment by daniel-j-h** [comment]
Thanks @TheMarex --- Travis was green before the rebase, let's get this in. Feel free to merge. I will skim the Wiki if we have any osmosis references there and will update appropriately.

**Pull request merged**
