### PR TITLE
Changes version to 5.6.3 for 5.6 branch

### PR DESCRIPTION
**Pull request by daniel-j-h**
5.6.3 for 5.6 branch

@karenzshea @TheMarex

### CODE REVIEW

**Comment by TheMarex** [comment]
> /home/travis/build/Project-OSRM/osrm-backend/unit_tests/util/io.cpp(130): fatal error in "io_incompatible_fingerprint": Should not get here

Fuck we can't merge this without breaking all our data files.

**Comment by daniel-j-h** [comment]
Ohshit

**Comment by TheMarex** [comment]
So my feeling here is that fixing this bug is worse (breaking all datasets) then not fixing it (allowing for mis-happens of loading 5.5 data into 5.6).

This is my fault, it totally slipped my mind that we _have_ to update this now.

**Comment by daniel-j-h** [comment]
Closing as not actionable. Master is already up to date, nothing we can do for the 5.6 branch.

**Pull request closed without merging**
