### PR TITLE
Add basic facades for Extractor and Contractor run methods

### PR DESCRIPTION
**Pull request by mloskot**
Based on idea suggested in comments to #3776, simplifies use of extractor and contractor as libraries.

------

Questions:

1. ~~Do I need to add tests for those trivial facades?~~
   * I've added two new tests: `extract.cpp` and `contract.cpp` with primitive tests verifying the `osrm::{extract|contract}` functions are callable. Placeholders easy to extend with more advanced use cases, if needed.
   * I've added two corresponding targets `library-{contract|extract}-tests`

2. ~~Do I need to add try-catch around `run` calls to ensure nothrow policy and plain exit codes are returned?~~
   * Answered in comments below and addressed in the PR updates.

### CODE REVIEW

**Comment by TheMarex** [comment]
> Do I need to add try-catch around run calls to ensure nothrow policy and plain exit codes are returned?

I just checked: You can safely ignore the exit codes: We will always `return 0` there. The `int` type seems to be a left-over from a refactor. You can safely change that to `void`. All errors should be reported by exceptions.

Thanks for finding the rough spots here! 👍 

If you are up for it: There is a define that we add for the library tests now: https://github.com/Project-OSRM/osrm-backend/blob/master/unit_tests/CMakeLists.txt#L67

You could use for example `OSRM_TEST_DIR "/monaco.om.pbf"` to actually run the `extract` function without error.

Another idea for a refactor: Make `osrm-extract` and `osrm-contract` in `src/tools/` use your new interface. That way it is ensured it will keep working. :-)

**Comment by mloskot** [comment]
> You can safely ignore the exit codes: (...) All errors should be reported by exceptions.

OK, I've just updated the PR.

> If you are up for it: There is a define that we add for the library tests now: https://github.com/Project-OSRM/osrm-backend/blob/master/unit_tests/CMakeLists.txt#L67

Yup, `CMakeLists.txt` update sets `OSRM_TEST_DATA_DIR` for the new test targets too.

> You could use for example OSRM_TEST_DIR "/monaco.om.pbf" to actually run the extract function without error.

That's my plan to add at least one test for successful run.

> Another idea for a refactor: Make osrm-extract and osrm-contract in src/tools/ use your new interface. 

Good idea, but I'd prefer to submit it as a separate PR (if/once this one is accepted).

**Comment by mloskot** [comment]
>> You could use for example OSRM_TEST_DIR "/monaco.om.pbf" to actually run the extract function without error.
> That's my plan to add at least one test for successful run.

Added `test_extract_with_valid_config` case.

**Comment by mloskot** [comment]
Cheers!

**Pull request merged**
