### PR TITLE
Set highway/route tags required but bridge optional in car profile

### PR DESCRIPTION
**Pull request by yuryleb**
This commit fixes issue #3588 "OSRM uses man_made=bridge lines to
route?" with exclusion of 'bridge' tag analisys from all profiles to
disable routing on bridges contours (with no highway tags)

### CODE REVIEW

**Comment by daniel-j-h** [comment]
You can't remove the bridge data we need it for moveable bridges and their capacity and duration tags

https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/lib/handlers.lua#L123-L143

Also can you adapt and / or add Cucumber tests to see the change in behavior.

**Comment by yuryleb** [comment]
It's very sad actually. I tried to rollback my changes and modify just profiles/lib/handlers.lua:
`-- handling movable bridges
function Handlers.handle_movables(way,result,data,profile)
  local bridge = data.bridge
  if bridge then
    local bridge_speed = profile.bridge_speeds[bridge]
    if bridge_speed and bridge_speed > 0 then
      local capacity_car = way:get_value_by_key("capacity:car")
      if capacity_car ~= 0 then
        result.forward_mode = profile.default_mode
        result.backward_mode = profile.default_mode
        local duration  = way:get_value_by_key("duration")
        if duration and durationIsValid(duration) then
          result.duration = math.max( parseDuration(duration), 1 )
        else
          result.forward_speed = bridge_speed
          result.backward_speed = bridge_speed
        end
      end
    else
      -- bridge type is not listed in bridge_speeds table => don't route
      result.forward_mode = mode.inaccessible
      result.backward_mode = mode.inaccessible
      return false
    end
  end
end`
That's to check if bridge tag value is listed in bridge_speed type and disable routing if not there. But unfortunately this has no effect. Do you see anything wrong here?

**Comment by yuryleb** [comment]
Found what's wrong: [the bridge](https://www.openstreetmap.org/way/117802273#map=15/59.9256/30.3954) I tried to bypass is movable too

**Comment by yuryleb** [comment]
I applied my changes to car profile only and updated all related tests. Should I do anything else to get this PR merged?

**Pull request merged**
