### PR TITLE
[NOT READY] General Many-To-Many plugin

### PR DESCRIPTION
**Pull request by TheMarex**
This plugin is in a very unfinished state. This pull request is just for tracking the progress.

TODO:

- [ ] Rebase on develop
- [ ] Evaluate what is actually implemented
- [ ] Add serialization to distance/time table
- [ ] Clean up code

### CODE REVIEW

**Comment by emiltin** [comment]
related issues:

Multi Source / Multi Target routing #1162
Travel time matrix with origins and destinations? #1075
Matrix and distances #1353

**Comment by frodrigo** [comment]
Any plan to integrate this feature ?
As side question, why add a new general_many_to_many.hpp and not support it in the already in place many_to_many.hpp ?

**Comment by frodrigo** [comment]
Released in 4.9.0 can be closed.

**Comment by TheMarex** [comment]
Not fully implemented, this includes distance as well.

**Comment by TheMarex** [comment]
Please reopen the PR for `master`, `develop` is going away.

**Pull request closed without merging**
