### PR TITLE
Increment feature id in tile speed layer

### PR DESCRIPTION
**Pull request by datwelk**
The tile layer currently contains the same id value of "1" for all linestring features in the speeds layer. There's a comment in the codebase that says the id should be incremented for each feature, but this does not happen for the linestring features. It does happen for the turn restriction features a few lines down.

This PR addresses the issue where linestring feature ids are not incremented.

### CODE REVIEW

**Review by mjjbell — APPROVED** [review]

**Comment by mjjbell** [comment]
LGTM. Can you add a changelog entry?

**Comment by datwelk** [comment]
@mjjbell Added changelog entry and rebased on master. Do I need to squash both commits into one or is it fine like this?

**Comment by mjjbell** [comment]
> @mjjbell Added changelog entry and rebased on master. Do I need to squash both commits into one or is it fine like this?

Thanks, it's fine, they will be squashed on merge.

**Comment by mjjbell** [comment]
Looks like some node tests are failing, because the underlying PBF varints for the IDs now make it bigger than previously expected. Can you update?

https://github.com/Project-OSRM/osrm-backend/blob/8526cc7d45adce9c352897acfd0366211e4f1d5e/test/nodejs/constants.js#L13

**Pull request merged**
