### PR TITLE
[Ready] Improves lane handling for subsequent going straight, resolves #2625

### LINKED ISSUE #2625: Handle subsequent lane changes going straight
At the moment we handle subsequent lane changes only if they happen in a [left / right turn](https://github.com/Project-OSRM/osrm-backend/blob/0e4061f85816b5499896022eb151a1402ae3aad0/src/engine/guidance/lane_processing.cpp#L83).
https://github.com/Project-OSRM/osrm-backend/pull/2612 adds roundabouts to the mix.

We should handle going straight as well.

### PR DESCRIPTION
**Pull request by daniel-j-h**
Before we only worked on subsequent quick left/right turns, as in:
`right, right` keeps the user on the rightmost lanes.

This changeset modifies the logic to work on any subsequent steps
that are "quick" and have lane information we can constrain later.

References:
- https://github.com/Project-OSRM/osrm-backend/issues/2625

Depends on:
- https://github.com/Project-OSRM/osrm-backend/pull/2636 (otherwise `UseLane` instructions are getting collapsed away)

### CODE REVIEW

**Comment by daniel-j-h** [comment]
Todo:
- [ ] more cucumber scenarios

**Comment by daniel-j-h** [comment]
More:
- [ ] refactor
- [ ] remove debug dumps
- [ ] squash

**Comment by MoKob** [comment]
@daniel-j-h can you re-open this PR on https://github.com/Project-OSRM/osrm-backend/pull/2614, since this is where https://github.com/Project-OSRM/osrm-backend/pull/2636 lives now

**Comment by daniel-j-h** [comment]
Refactored, squashed --- @MoKob rebase + merge scheduled for Monday.

**Comment by daniel-j-h** [comment]
Rebased against your advanced lanes branch @MoKob. Feel free to merge.

**Comment by daniel-j-h** [comment]
Re-opening against advanced-lanes https://github.com/Project-OSRM/osrm-backend/pull/2671.

**Pull request closed without merging**
