### PR TITLE
Experimental: test simple Travis CI setup using Nix dev environment

### PR DESCRIPTION
**Pull request by daniel-j-h**
Broken out from https://github.com/Project-OSRM/osrm-backend/pull/1855: let's see how Travis CI likes the Nix dev environment.

### CODE REVIEW

**Comment by daniel-j-h** [comment]
Hmm the Travis build didn't start at all? Can't find it.

**Comment by daniel-j-h** [comment]
Second push, second time Travis builds do not start up.
Hm, there seems to be something wrong with the .travis.yml I assume.

**Comment by TheMarex** [comment]
@daniel-j-h I think there is a `.travis.yml` checker. They have a `cli` util.

**Comment by daniel-j-h** [comment]
Travis builds are not starting; I created a repository only containing the Travis and Nix config:
https://travis-ci.org/daniel-j-h/nix-travis-setup
Travis is able to start builds for this repository.

**Comment by daniel-j-h** [comment]
Travis is green! :tada: https://travis-ci.org/Project-OSRM/osrm-backend/builds/103619184

**Comment by TheMarex** [comment]
Not actionable, closing for now.

**Pull request closed without merging**
