### PR TITLE
correct comments for "compress edge if it crosses a traffic signal"

### PR DESCRIPTION
**Pull request by wangyoucao577**
# Issue
https://github.com/Project-OSRM/osrm-backend/issues/5385

What issue is this PR targeting? If there is no issue that addresses the problem, please open a corresponding issue and link it here.

Please read our [documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/releasing.md) on release and version management.
If your PR is still work in progress please attach the relevant label.

## Tasklist

 - [ ] ~~CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))~~
 - [ ] ~~update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)~~
 - [ ] ~~add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md)~~
 - [ ] review
 - [x] adjust for comments
 - [ ] ~~cherry pick to release branch~~

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?
 
PR https://github.com/Project-OSRM/osrm-backend/pull/4327 implemented functions, but the comments wasn't up to date. When I read codes here, it makes me confused. So I'm going to help to correct the comments.

### CODE REVIEW

**Comment by wangyoucao577** [comment]
Hi, can anyone help to review this issue? It's just correct comments and has been waiting for about 2 months. Thanks!

**Comment by wangyoucao577** [comment]
Hi, anyone can help to review this PR? Thanks!

**Comment by akashihi** [comment]
> Hi, anyone can help to review this PR? Thanks!

Could you please provide more context?

**Comment by wangyoucao577** [comment]
@akashihi 

> > Hi, anyone can help to review this PR? Thanks!
> 
> Could you please provide more context?

The comment tells that `Do not compress edge if it crosses a traffic signal`. However, when I read the code, I found that the logic under the comment do compressing edge that crosses a `traffic signal`. I have described the behavior [here](https://github.com/Telenav/open-source-spec/blob/master/osrm/doc/how_osrm_calculate_weight_and_duration.md#add-penalty-for-compressible-traffic_signals). After blame the changes, the author only comment the old comments in PR https://github.com/Project-OSRM/osrm-backend/pull/4327/ when made the changes, but didn't remove them or correct them. So I'd like to correct the comments to avoid confuse people.

**Comment by akashihi** [comment]
@wangyoucao577 Thank you for clarification!

**Comment by wangyoucao577** [comment]
So would you please help to merge the PR either? I can not merge it by myself. Thanks!

**Comment by akashihi** [comment]
> So would you please help to merge the PR either? I can not merge it by myself. Thanks!

Sorry! Completely forgot about it :(

**Pull request merged**
