### PR TITLE
Use Boost.Beast to parse HTTP request

### PR DESCRIPTION
**Pull request by SiarheiFedartsou**
# Issue

### Motivation
1. I want to use body of POST request for something and it looks like with current implementation I will have to manually implement parsing of the body. While I'll probably won't share in public this feature I am going to work on, at the same time this change looks as something useful for other people.
2. Boost.Beast feels more well-tested and reliable rather than our custom HTTP parsing.

## Tasklist

 - [ ] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md))
 - [ ] review
 - [ ] adjust for comments
 - [ ] cherry pick to release branch

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by SiarheiFedartsou** [comment]
@mjjbell would appreciate your opinion here :)

**Comment by mjjbell** [comment]
The HTTP server is effectively [just the Boost.Asio demo code](https://github.com/Project-OSRM/osrm-backend/pull/6113), so assuming Boost.Beast plays well with it (which I think it does), then I agree that it makes sense to use request parsing that is actively maintained.

With regards to POST requests, this has been discussed a few times in the past, #4211 is probably the best summary.
I think it boiled down to the fact that the HTTP server is aforementioned demo code, so it would be advisable to bind a production-grade HTTP server to libosrm or use the Node bindings, instead of hacking on the demo code.  It is the [most popular](https://github.com/Project-OSRM/osrm-backend/issues/5794) requested feature though.

But if it's for your own purposes, then none of this matters too much :slightly_smiling_face: .

**Comment by SiarheiFedartsou** [comment]
> The HTTP server is effectively [just the Boost.Asio demo code](https://github.com/Project-OSRM/osrm-backend/pull/6113), so assuming Boost.Beast plays well with it (which I think it does), then I agree that it makes sense to use request parsing code that is actively maintained.
> 
> With regards to POST requests, this has been discussed a few times in the past, #4211 is probably the best summary. I think it boiled down to the fact that the HTTP server is aforementioned demo code, so it would be advisable to bind a production-grade HTTP server to libosrm or use the Node bindings, instead of hacking on the demo code. It is the [most popular](https://github.com/Project-OSRM/osrm-backend/issues/5794) requested feature though.
> 
> But if it's for your own purposes, then none of this matters too much 🙂 .

So speaking other words you want to say that migration to some “adult” HTTP server will give more value to the project than this PR?

**Comment by SiarheiFedartsou** [comment]
> > The HTTP server is effectively [just the Boost.Asio demo code](https://github.com/Project-OSRM/osrm-backend/pull/6113), so assuming Boost.Beast plays well with it (which I think it does), then I agree that it makes sense to use request parsing code that is actively maintained.
> > With regards to POST requests, this has been discussed a few times in the past, #4211 is probably the best summary. I think it boiled down to the fact that the HTTP server is aforementioned demo code, so it would be advisable to bind a production-grade HTTP server to libosrm or use the Node bindings, instead of hacking on the demo code. It is the [most popular](https://github.com/Project-OSRM/osrm-backend/issues/5794) requested feature though.
> > But if it's for your own purposes, then none of this matters too much 🙂 .
> 
> So speaking other words you want to say that migration to some “adult” HTTP server will give more value to the project than this PR?

If so can you recommend what can be used? As I can see what @daniel-j-h used in https://github.com/daniel-j-h/libosrm-http-casablanca is in maintenance mode.

**Comment by SiarheiFedartsou** [comment]
> > > The HTTP server is effectively [just the Boost.Asio demo code](https://github.com/Project-OSRM/osrm-backend/pull/6113), so assuming Boost.Beast plays well with it (which I think it does), then I agree that it makes sense to use request parsing code that is actively maintained.
> > > With regards to POST requests, this has been discussed a few times in the past, #4211 is probably the best summary. I think it boiled down to the fact that the HTTP server is aforementioned demo code, so it would be advisable to bind a production-grade HTTP server to libosrm or use the Node bindings, instead of hacking on the demo code. It is the [most popular](https://github.com/Project-OSRM/osrm-backend/issues/5794) requested feature though.
> > > But if it's for your own purposes, then none of this matters too much 🙂 .
> > 
> > 
> > So speaking other words you want to say that migration to some “adult” HTTP server will give more value to the project than this PR?
> 
> If so can you recommend what can be used? As I can see what @daniel-j-h used in https://github.com/daniel-j-h/libosrm-http-casablanca is in maintenance mode.

I am thinking about https://github.com/cesanta/mongoose

**Comment by mjjbell** [comment]
> So speaking other words you want to say that migration to some “adult” HTTP server will give more value to the project than this PR?

It would, but small improvements like this are also useful. Was just giving you the full context on why there is no POST support.

**Comment by SiarheiFedartsou** [comment]
> It would, but small improvements like this are also useful

Do you think this PR should be merged then?

**Review by mjjbell — APPROVED** [review]

**Pull request merged**
