### PR TITLE
[Not Ready] Custom Turn Penalties from Files

### PR DESCRIPTION
**Pull request by daniel-j-h**
WIP. Tracks progress for https://github.com/Project-OSRM/osrm-backend/issues/1830.

### CODE REVIEW

**Comment by daniel-j-h** [comment]
- [ ] settle on format (e.g. `a,via,b,penalty` csv)
- [ ] let `osrm-extract` serialize a `edge-based-node` to `(a,via,b)` lookup table
- [ ] let `osrm-contract` loop over all `edge-based-node`s and do a lookup, bringing in the penalty (if exists)

**Comment by daniel-j-h** [comment]
For the record: not working on this at the moment as I'm heads up on more important issues (i.e. unit tests for v5). Cherry-picking the include fixes into develop.

**Comment by daniel-j-h** [comment]
Format settled as of https://github.com/Project-OSRM/osrm-backend/issues/1830#issuecomment-198138563.

**Comment by TheMarex** [comment]
Please reopen the PR for `master`, `develop` is going away.

**Pull request closed without merging**
