### PR TITLE
test VS2015 build

### PR DESCRIPTION
**Pull request by DennisOSRM**
background: http://www.appveyor.com/blog/2015/01/20/visual-studio-2015-ctp-image

### CODE REVIEW

**Comment by emiltin** [comment]
Travis failed due to a ruby timeout when launching osrm-routed. The timeout is currently set yo 60 seconds. We can increase it if we want.

**Comment by DennisOSRM** [comment]
thanks @emiltin. I'll rerun for the sake of having an all green. The Travis environment is rather fishy.

**Comment by DennisOSRM** [comment]
@alex85k would love to have your opinion on this

**Comment by alex85k** [comment]
Swithcing to VS2015 is may be harder. cmake redefinesthe compiler, ``-G "Visual Studio 14 2015 Win64" ``` is needed. Currently it still uses MSVC 18.0 from VS2013...

Most likely, the dependencies pack will be incompatible (however, the libs from https://github.com/BergWerkGIS/mapnik-dependencies are tested on VS2015).

Switching to VS2015 preview will certainly be needed after VS2015 Express release but I am not sure we should drop VS2013+CTP (most popular) version now... Better have both but that means two dependencies packs.

**Comment by DennisOSRM** [comment]
Alright, then let's revisit once the software is actually released.

**Pull request closed without merging**
