### PR TITLE
DNM: Quick hack to run tests against Valhalla.

### PR DESCRIPTION
**Pull request by danpat**
# Issue

With the Valhalla folks joining most of the OSRM developers at Mapbox, we're starting to do some side-by-side comparisons to get a good idea of where each engine's strengths/weaknesses lie.

This PR is a quick prototype to enable the Valhalla engine to be used for some of OSRM's cucumber tests.  There are many tests that will likely never run (fundamentally incompatible APIs), but there is a lot in common that we can compare.  This PR uses the `&format=osrm` feature of Valhalla to feed the Valhalla response into the existing test suite.

I think it's highly unlikely that we'll merge this PR, but I'm opening it for visibility and feedback.

To run tests, you'll need to set some environment variables:

Here's an example showing where OSRM gives `off ramp slight right`, but Valhalla gives `off ramp right`:

Example invocation:
```bash
$ VALHALLA_HOME=/home/danpat/valhalla \
  OSRM_LOAD_METHOD=valhalla \
  CUCUMBER_TIMEOUT=35000 \
  OSRM_PORT=8002 \
  ./node_modules/.bin/cucumberjs ./features/guidance/motorway.feature:8
```

Example output:
```
1) Scenario: Ramp Exit Right - features/guidance/motorway.feature:8
   Step: When I route I should get - features/guidance/motorway.feature:20
   Step Definition: features/step_definitions/routing.js:4
   Message:
     Tables were not identical:
     | waypoints | route         |     turns                               |
     | a,e       | abcde,abcde   |     depart,arrive                       |
     | a,g       | abcde,bfg,bfg | (-) depart,off ramp slight right,arrive |
     | a,g       | abcde,bfg,bfg | (+) depart,off ramp right,arrive        |

```

Once tests are run, you can convert the test output into readable HTML form with:

```
$ mkdir report
$ node scripts/tests2doc.js > report/index.html
```

Then open `report/index.html` in a web browser.  Example output here: http://danpat.net/osrm/guidancecompare/

### CODE REVIEW

**Comment by danpat** [comment]
This branch can now publish a visual report from the cucumber tests.  I've pushed a copy of some of the results here:

http://danpat.net/osrm/guidancecompare/

**Comment by gknisely** [comment]
@danpat  `node scripts/tests2doc.js > report/index.html` does not seem to work for me.

`more index.html`

`<!DOCYPE html>
<html>
<head>
  <style>
    body { font-family: sans-serif; }
    .results td { padding-left: 1em; font-family: monospace; }
    .results th { padding-left: 1em; }
    .scenario.error { background: #fbb; }
    .error { color: red; }
  </style>
  <body>
Notes: OSRM "slight" and "sharp" indicators have been removed for comparison purposes.
<hr/>



</body>
</html>
`

**Comment by gknisely** [comment]
@danpat this maybe due to config issues on my side.  I am checking on this

**Comment by gknisely** [comment]
@danpat it looks like the pbf files are missing.  
`Error: Command failed: /data/mapbox/valhalla/valhalla_build_tiles -c /data/mapbox/osrm-backend/test/cache/guidance/advanced-lanes.feature/ea5fdb02a56fc0fac6a125af754a9f0a/569c23621274dbf1d2cf43876dc66dde/243_check_sliproad_handler_loops_exit_condition_issue_2896_valhalla_config.json /data/mapbox/osrm-backend/test/cache/guidance/advanced-lanes.feature/ea5fdb02a56fc0fac6a125af754a9f0a/569c23621274dbf1d2cf43876dc66dde/243_check_sliproad_handler_loops_exit_condition_issue_2896.pbf`

the 243_check_sliproad_handler_loops_exit_condition_issue_2896.osm file exists but not the 243_check_sliproad_handler_loops_exit_condition_issue_2896.pbf file.  

Is there a pre-step that I am missing?

**Comment by danpat** [comment]
@gknisely arg, I forgot this depends on `/usr/local/bin/osmium` to convert the OSM XML generated by the code into PBF format for Valhalla.

https://github.com/osmcode/osmium-tool/

The path to the tool is currently hard-coded here:

https://github.com/Project-OSRM/osrm-backend/blob/test_valhalla_guidance/features/support/data.js#L186

if you have `osmium` somewhere else on your system already, modify that value.  I'll see if I can find a way to make this portable.

**Pull request closed without merging**
