### PR TITLE
Add to car profile missing BE:motorway maxspeed_table exceptions osm-fr/osmose-backend#232

### PR DESCRIPTION
**Pull request by frodrigo**
The BE:motorway maxspeed_table exceptions is missing.

### CODE REVIEW

**Comment by daniel-j-h** [comment]
Can you update `taginfo.json`

**Comment by frodrigo** [comment]
Done. I also fixed the taginfo.json file.

**Comment by daniel-j-h** [comment]
Travis build with taginfo validator was still failing - could you take another look @frodrigo.

**Comment by frodrigo** [comment]
Ok. I fixed the test.

**Pull request merged**
