### PR TITLE
include lock_types.hpp

### PR DESCRIPTION
**Pull request by BergWerkGIS**
try #include <boost/thread/lock_types.hpp>

### CODE REVIEW

**Comment by BergWerkGIS** [comment]
Neither AppVeyor nor Travis pick this up, why??

**Comment by daniel-j-h** [comment]
Interesting. Probably a glitch. I would either try re-toggling via an empty commit or amend your commit and force push or a new pull request if nothing else helps.

**Comment by BergWerkGIS** [comment]
ah, only `develop` and PRs against it get built.

But a new PR (https://github.com/Project-OSRM/osrm-backend/pull/1994) against `develop` doesn't worth either, because it is not mergeable:


```
AppVeyor was unable to build non-mergeable pull request
```

Mind trying the include (https://github.com/Project-OSRM/osrm-backend/compare/win-lock-types#diff-5b4f2be9192822635353156224b4541dR25) in the c++14 branch?

**Comment by daniel-j-h** [comment]
Oh sure, feel free to add it to the c++14 branch.

**Pull request closed without merging**
