### PR TITLE
Fix build on CentOS

### PR DESCRIPTION
**Pull request by rkcpi**
# Issue

Fixes build on CentOS systems which doesn't have gcc ready for C++14 yet.

Fixes issue #2804

### CODE REVIEW

**Comment by TheMarex** [comment]
Doesn't `c++1y` mean `c++11` on older compilers? We switched to C++14 a while ago and just didn't get around to clean up the legacy code that backported some 14 functionality (e.g. http://en.cppreference.com/w/cpp/memory/unique_ptr/make_unique)

**Comment by MoKob** [comment]
From what I've read `c++1y` is the respective draft of `c++14` just like `c++11` was referred to by `c++0x`. Using a draft only does not seem a valid step in our progression to me.

**Comment by rkcpi** [comment]
This is a change proposed by @daniel-j-h yesterday in irc:
```
11:56:40 <   danieljh> rkcpi: if it works fine with "c++1y" instead can you open a pull request with that change and see how travis likes it?
```
Is there another valid approach to still be able to build with gcc on CentOS?

**Comment by TheMarex** [comment]
Merging here. Note that on newer compiler `c++1y` is just an alias for `c++14` so it doesn't change anything for our current setup.

**Pull request merged**
