### PR TITLE
Add split_edges flag

### LINKED ISSUE #3625: map matching returns name for the wrong direction
Using the v5.5.4 release, I notice that map matching can map a trace to the wrong direction. Here is a small example that reproduces the problem.

Given the following trace/query, which goes from west to east:

`/match/v1/car/-120.147778,34.392861;-120.147695,34.392889?annotations=true&overview=false`

and the following OSM:
```
<osm generator="test" version="0.6">
<node id="1" lon="-120.1467783" lat="34.3932086" version="1" changeset="1" timestamp="2017-01-19T18:37:02Z" />
<node id="2" lon="-120.147782" lat="34.39286" version="1" changeset="1" timestamp="2017-01-19T18:37:02Z" />
<way id="1" version="1" changeset="1" timestamp="2017-01-19T18:37:29Z">
<nd ref="1" />
<nd ref="2" />
<tag k="highway" v="secondary" />
<tag k="oneway" v="yes" />
<tag k="name" v="westbound" />
</way>
<way id="2" version="1" changeset="1" timestamp="2017-01-19T18:37:29Z">
<nd ref="2" />
<nd ref="1" />
<tag k="highway" v="secondary" />
<tag k="oneway" v="yes" />
<tag k="name" v="eastbound" />
</way>
</osm>
```

the resulting matched name is the wrong direction (westbound) 
```
{"tracepoints":[{"location":[-120.147778,34.392861],"hint":"AAAAAAEAAIAEAAAAUQAAAAEAAAAAAAAAAAAAAAAAAAABAACAvrDW-B3LDAK-sNb4HcsMAgAAAQF_0OeL","matchings_index":0,"waypoint_index":0,"name":"westbound"},{"location":[-120.147695,34.392889],"hint":"AAAAAAEAAIAEAAAASgAAAAgAAAAAAAAAAAAAAAAAAAABAACAEbHW-DnLDAIRsdb4OcsMAgAAAQF_0OeL","matchings_index":0,"waypoint_index":1,"name":"westbound"}],"matchings":[{"distance":8.2,"duration":0.7,"legs":[{"distance":8.2,"steps":[],"duration":0.7,"annotation":{"nodes":[2,1],"datasources":[0],"duration":[7.4],"distance":[8.22993]},"summary":""}],"confidence":0.980289}],"code":"Ok"}
```

Note that my OSM is such that both ways share the same nodes. I remember seeing this same problem in v4.x and it was fixed in v4.x. But this does not seem to work in v5.x.

I'd like to be upgrade from v4 to v5 and any help would be appreciate. Thanks

### PR DESCRIPTION
**Pull request by oxidase**
# Issue

PR adds a `split_edge` flag for #3869 to avoid workarounds

## Tasklist
 - [x] Check if it fixes #3625 and #3775 
 - [x] Add some words in docs
 - [x] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [x] add regression / cucumber cases (see docs/testing.md)
 - [x] review
 - [ ] adjust for comments

## Requirements / Relations
 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by oxidase** [comment]
rebased onto `fix/segment-end-points` so  #3873 must be merged before

**Comment by daniel-j-h** [comment]
Great! Can you add a changelog entry and update the docs at docs/profiles.md.

**Comment by emiltin** [comment]
how does a profile taking elevation into account know when to split? or will such a profile simply ask to split all ways? typically, the elevation lookup is done in the segment function, not the way function.

**Comment by daniel-j-h** [comment]
Yes. always split if you need the segment function being called for forward and backward direction.

Otherwise we only have a single non-split edge.

**Comment by emiltin** [comment]
then maybe it should be a global flag instead of a flag in the result object in the way function?

**Comment by oxidase** [comment]
@emiltin ok, i don't see atm a use case for setting the flag to a proper subset of ways.

**Comment by daniel-j-h** [comment]
cc @MichalPP @OnlyMate - can you test against this branch, this should resolve all your issues.

Should land in master soon, too.

**Comment by OnlyMate** [comment]
I'll test it soon. 👍

**Comment by OnlyMate** [comment]
Works like charm! Here my results:

## OSM data
```xml
<?xml version='1.0' encoding='UTF-8'?>
<osm version='0.6' upload='true' generator='JOSM'>
  <bounds minlat='47.1476083' minlon='9.5186931' maxlat='47.1477287' maxlon='9.5191196' origin='CGImap 0.5.8 (16004 thorn-02.openstreetmap.org)' />
  <node id='3668934653' timestamp='2015-07-27T16:12:38Z' uid='2110714' user='captain_slow' visible='true' version='1' changeset='32912926' lat='47.1470504' lon='9.5216004' />
  <node id='3668934654' timestamp='2015-07-27T16:12:38Z' uid='2110714' user='captain_slow' visible='true' version='1' changeset='32912926' lat='47.1475196' lon='9.5208335' />
  <node id='3668934655' timestamp='2015-07-27T16:12:38Z' uid='2110714' user='captain_slow' visible='true' version='1' changeset='32912926' lat='47.1475881' lon='9.520664' />
  <node id='3668934656' timestamp='2015-07-27T16:12:38Z' uid='2110714' user='captain_slow' visible='true' version='1' changeset='32912926' lat='47.1476023' lon='9.5204022' />
  <node id='3668934657' timestamp='2015-07-27T16:12:39Z' uid='2110714' user='captain_slow' visible='true' version='1' changeset='32912926' lat='47.1476049' lon='9.5197557' />
  <node id='3668934658' timestamp='2015-07-27T16:12:39Z' uid='2110714' user='captain_slow' visible='true' version='1' changeset='32912926' lat='47.1476919' lon='9.5190052' />
  <node id='3668934659' timestamp='2015-07-27T16:12:39Z' uid='2110714' user='captain_slow' visible='true' version='1' changeset='32912926' lat='47.1476923' lon='9.5187653' />
  <node id='3668934660' timestamp='2015-07-27T16:12:39Z' uid='2110714' user='captain_slow' visible='true' version='1' changeset='32912926' lat='47.1476363' lon='9.5185668' />
  <way id='28712192' timestamp='2015-07-27T16:12:48Z' uid='2110714' user='captain_slow' visible='true' version='4' changeset='32912926'>
    <nd ref='3668934653' />
    <nd ref='3668934654' />
    <nd ref='3668934655' />
    <nd ref='3668934656' />
    <nd ref='3668934657' />
    <nd ref='3668934658' />
    <nd ref='3668934659' />
    <nd ref='3668934660' />
    <tag k='highway' v='residential' />
    <tag k='motorcar' v='destination' />
    <tag k='motorcycle' v='destination' />
    <tag k='name' v='Brandiserweg' />
  </way>
</osm>
```

## Results
### Force splitting = false
```lua
properties.force_split_edges = false
```
bildschirmfoto 2017-03-30 um 11 45 28

### Force splitting = true
```lua
properties.force_split_edges = true
```
bildschirmfoto 2017-03-30 um 11 46 57

### Force splitting = false and different forward/backward speed
```lua
properties.force_split_edges = false

function way_function (way, result)
  local highway = way:get_value_by_key("highway")
  local name = way:get_value_by_key("name")

  if name then
    result.name = name
  end

  result.forward_mode = mode.cycling
  result.backward_mode = mode.cycling

  result.forward_speed = 15
  result.backward_speed = 15.01
end
``` 
Works like force splitting = true. 

Thank you very much!

**Pull request merged**
