### PR TITLE
Add missing files in exception message

### PR DESCRIPTION
**Pull request by rgugliel**
# Issue

What issue is this PR targeting? If there is no issue that addresses the problem, please open a corresponding issue and link it here.

Please read our [documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/releasing.md) on release and version management.
If your PR is still work in progress please attach the relevant label.

## Tasklist

 - [x] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md)
 - [ ] review
 - [ ] adjust for comments
 - [ ] cherry pick to release branch

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by akashihi** [comment]
@rgugliel Could you please resolve conflicts, so i'll be able to merge it?

**Comment by rgugliel** [comment]
Should be fine now. Let me know if there are further actions to perform.

**Review by akashihi — APPROVED** [review]

**Comment by akashihi** [comment]
@rgugliel Formatting need to be fixed by calling ./scripts/format.sh

And MSVC build is failing with 'error C2668: 'boost::filesystem::is_regular_file': ambiguous call to overloaded function', could you please take a look?

**Comment by rgugliel** [comment]
Maybe we can just decline and redo at some point. I started this tiny change two years ago and don't have MSVC so checking will be difficult.

**Comment by akashihi** [comment]
I'm not a Windows guy, but have MSVC :) So will take a look later and do a PR for your PR  maybe :)

**Comment by akashihi** [comment]
@rgugliel 

Replacing `boost::filesystem::is_regular_file({base_path.string() + fileName.string()})` with `boost::filesystem::is_regular_file(boost::filesystem::path(base_path.string() + fileName.string()))` fixes windows compilation. Could you please update your PR (and format&rebase it)?

**Comment by rgugliel** [comment]
Sorry for the delay. When I run the format script, I get a huge amount of changes (mostly adding // namespace) in files that I did not change, so I did not push that, yet.

**Pull request merged**
