### PR TITLE
Solving problem with g++8 and boost libs:

### PR DESCRIPTION
**Pull request by stastnypremysl**
osrm-backend/src/storage/io_config.cpp:18:89: error: call of overloaded ‘is_regular_file(<brace-enclosed initializer list>)’ is ambiguous
         if (!boost::filesystem::is_regular_file({base_path.string() + fileName.string()}))
                                                                                         ^
In file included from /usr/local/include/boost/filesystem.hpp:17,
                 from /home/premy/packages/osrm-backend/include/storage/io_config.hpp:8,
                 from /home/premy/packages/osrm-backend/src/storage/io_config.cpp:1:
/usr/local/include/boost/filesystem/operations.hpp:473:8: note: candidate: ‘bool boost::filesystem::is_regular_file(const boost::filesystem::path&)’
   bool is_regular_file(const path& p)  {return is_regular_file(detail::status(p));}
        ^~~~~~~~~~~~~~~
In file included from /usr/local/include/boost/filesystem.hpp:17,

# Issue

What issue is this PR targeting? If there is no issue that addresses the problem, please open a corresponding issue and link it here.

Please read our [documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/releasing.md) on release and version management.
If your PR is still work in progress please attach the relevant label.

## Tasklist

 - [ ] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md)
 - [ ] review
 - [ ] adjust for comments
 - [ ] cherry pick to release branch

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by stastnypremysl** [comment]
I have added travis for g++8 and it have thrown new errors because of -Werror=cast-function-type flag.
On my machine, g++8 build already works well (with many warnings), but Travis won't let it pass.

The errors:
```
\home/travis/build/Project-OSRM/osrm-backend/node_modules/nan/nan.h:2208:62: error: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Werror=cast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
In file included from /home/travis/build/Project-OSRM/osrm-backend/src/nodejs/node_osrm.cpp:16:
/home/travis/build/Project-OSRM/osrm-backend/include/nodejs/node_osrm.hpp: At global scope:
/home/travis/build/Project-OSRM/osrm-backend/include/nodejs/node_osrm.hpp:42:132: error: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Werror=cast-function-type]
 NODE_MODULE(osrm, node_osrm::Engine::Init)
                                                                                                                                    ^
```

```
/home/travis/build/Project-OSRM/osrm-backend/build-osrm/src/nodejs/node/v10.15.3/include/v8.h:9502:16: error: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Werror=cast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/Project-OSRM/osrm-backend/build-osrm/src/nodejs/node/v10.15.3/include/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
/home/travis/build/Project-OSRM/osrm-backend/node_modules/nan/nan_object_wrap.h:66:61:   required from here
/home/travis/build/Project-OSRM/osrm-backend/build-osrm/src/nodejs/node/v10.15.3/include/v8.h:9502:16: error: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Werror=cast-function-type]
```

**Comment by stastnypremysl** [comment]
Maybe solution would be to write new function instead of using the reinterpret_cast. 
Should I do it?

**Comment by stastnypremysl** [comment]
Ohh, I understand it (maybe) now. There is probably a problem with node.js binding.

**Comment by stastnypremysl** [comment]
There is problem in nodejs nan libraries: https://github.com/nodejs/nan/issues/807

**Comment by stastnypremysl** [comment]
@gardster 
It finally works, but I think, the flag should be moved to cmake file. And I don't have no idea into which one.

**Comment by gardster** [comment]
Yes it seems, that nan project won't to fix this behavior. Can you rebase your PR to reduce the number of commits . And then I can merge this PR.

**Comment by gardster** [comment]
@stastnypremysl I think we can leave this flag in the Travis configuration. I hope that this behavior wouldn't be permanent and after some time nodejs will fix this issue or GCC exclude this flag form extra checks. So this flag in Travis configuration will be an additional purpose to check behavior in the future.

**Comment by stastnypremysl** [comment]
@gardster Better?

**Comment by stastnypremysl** [comment]
Thanks.

**Pull request merged**
