### PR TITLE
Remove unconnected boundary nodes from partition

### PR DESCRIPTION
**Pull request by TheMarex**
# Issue

Addresses ~#3780~ and #3818 and refactors assigning IDs from node-based edges to edge-based edges.

We now chose the `BisectionID` of the side that would induce the least amount of boundary edges (since we are assigning `BisectionID`s and not `CellID`s this is only heuristic, since two different `BisectionID`s can later be contained in the same cell).

We also remove all unconnected boundary nodes.

## Tasklist
 - [x] review
 - [x] adjust for comments

### CODE REVIEW

**Comment by TheMarex** [comment]
@oxidase ah sorry my bad, renamed the PR title. Going to squash the commits before merging, the reverts are just there for transparency.

**Comment by oxidase** [comment]
@TheMarex it is really hard to compare heuristics, because non-covered edge cases could give different results. I checked only two cases:
*  `./osrm-partition bayern-latest.osrm` on master and the branch: number of unconnected nodes goes from 0,2,3,4 to 18,19 (numbers are different between runs, because partitioning is not stable). 
* `./osrm-partition germany-latest.osrm` number of unconnected nodes goes from 43,45 to 89,94. 

These numbers are really small (~10^-6 part of all nodes), so the difference is almost insignificant. 

I think it is better to use heuristic as simple as possible or even better avoid any kind by partitioning the edge-based graph, but don't know if it must be prioritized because of  so minor win.

**Comment by TheMarex** [comment]
@oxidase I will try your test datasets. This method should guarantee exactly zero unconnected boundary nodes.

**Comment by TheMarex** [comment]
@oxidase fixed a bug in the code that breaks the partition, which was causing this weirdness.

Did some investigation around the increased border nodes: Picking the minimum border edge `BisectionID` does actually decrease quality. I tried a few combinations and surprisingly picking `u` for the forward and `v` for the backward node works the best.

My hypothesis is this is because this comes closest to a partitioning on the actual embedding. (forward node would be represented by the start of the edge and the backward node by the target)

**Pull request merged**
