### PR TITLE
Fix performance issues after migration to sol2 3.3.0

### PR DESCRIPTION
**Pull request by SiarheiFedartsou**
# Issue

People are reporting performance issues after merge of https://github.com/Project-OSRM/osrm-backend/pull/6279, I reproduced it and it turned out that now we are copying the whole `relations` container on each invocation of node_function 🤦🏻 

Some discussions in:

https://github.com/Project-OSRM/osrm-backend/issues/6302
https://github.com/Project-OSRM/osrm-backend/issues/6297
## Tasklist

 - [ ] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md))
 - [ ] review
 - [ ] adjust for comments
 - [ ] cherry pick to release branch

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Review by KaSakee — APPROVED** [review]
It makes sense to use reference_wrapper, Nice job.

**Comment by mjjbell** [comment]
Thanks, I missed this in the original PR.

To confirm my understanding:
- the `sol2` upgrade has changed the behaviour of passing const references to user-defined types. It will now copy the value (as indicated by the Node [copy constructor error](https://github.com/Project-OSRM/osrm-backend/pull/6279#discussion_r917304115))
- `ExtractionRelationContainer` had a copy constructor, so this is the performance regression.
- Wrapping non-const references is not strictly necessary as the behaviour has not changed, but it makes the arguments consistent / future-proofed.

Is this right?

**Comment by SiarheiFedartsou** [comment]
> the sol2 upgrade has changed the behaviour of passing const references to user-defined types

Tbh I haven't seen it in sol2's changelog, but I assume so. It will now copy the value

>(as indicated by the Node https://github.com/Project-OSRM/osrm-backend/pull/6279#discussion_r917304115)

Yes, and it is my fault that I didn't pay enough attention to it 🤦🏻 

> ExtractionRelationContainer had a copy constructor, so this is the performance regression.

Yes.

> Wrapping non-const references is not strictly necessary as the behaviour has not changed, but it makes the arguments consistent / future-proofed.

In other words you are curious here why didn't we have problems for the cases when something was supposed to be changed by Lua script? I.e. if it was copied, i.e. we would change the copy in the script then behaviour was expected to be changed in this case? Tbh I didn't think about that. Probably worth looking a bit deeper into it to be 100% confident. 
There is [a paragraph about this](https://sol2.readthedocs.io/en/latest/functions.html#function-argument-handling) in sol2 docs. They say it copies C++ types by default 🤔 

Screenshot 2022-08-15 at 22 34 18

I'll probably be able to dig into it in the nearest days and have better answers. WDYT?

**Comment by mjjbell** [comment]
> > Wrapping non-const references is not strictly necessary as the behaviour has not changed, but it makes the arguments consistent / future-proofed.
> 
> In other words you are curious here why didn't we have problems for the cases when something was supposed to be changed by Lua script? I.e. if it was copied, then we would change the copy in the script -> behaviour was expected to be changed in this case? Tbh I didn't think about that. Probably worth looking a bit deeper into it to be 100% confident. There is [a paragraph about this](https://sol2.readthedocs.io/en/latest/functions.html#function-argument-handling) in sol2 docs. They say it copies C++ types by default thinking
> 
> Screenshot 2022-08-15 at 22 34 18
> 
> I'll probably be able to dig into it in the nearest days and have better answers. WDYT?

Yes, although it has the exact [same wording](https://sol2.readthedocs.io/en/v2.20.6/functions.html) in the old docs, but we know something has changed since then.
I think it's fine as all of the tests would have failed. Judging by this relatively recent [comment](https://github.com/ThePhD/sol2/issues/1070#issuecomment-747869536), what we are seeing is now aligned with the intended behaviour.

**Comment by mjjbell** [comment]
And the `std::ref` wrapping ensures it's not a problem in any case :+1:

**Review by mjjbell — APPROVED** [review]

**Pull request merged**
