### PR TITLE
Handle motorway forks with links as normal motorway intersections

### PR DESCRIPTION
**Pull request by oxidase**
# Issue

If a motorway fork intersection has links the motorway handler can assign incorrect `Left` modifier
screenshot from 2018-02-16 11-54-20
http://map.project-osrm.org/?z=18&center=53.461582%2C-2.244827&loc=53.461383%2C-2.245116&loc=53.462187%2C-2.245100&hl=en&alt=0

PR changes handling of motorway intersections to a case of a normal motorway passing some ramps if `exiting_motorways` is not equal to `valid_exits`.

## Tasklist

 - [x] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [x] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md)
 - [x] review
 - [x] adjust for comments
 - [ ] cherry pick to release branch

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by jguthrie100** [comment]
Worth noting as well that the osrm map tile at that location needs to be updated.. https://www.openstreetmap.org/directions?engine=graphhopper_car&route=53.30787%2C-2.37205%3B53.46230%2C-2.24521

**Comment by oxidase** [comment]
@jguthrie100 :wave: I have found the issue while looking at #4892. The data fix for #4892 will be visible after the OSM change will propagate in the data pipeline. But  correct instructions at the intersection will be visible after the next OSRM release.

**Comment by jguthrie100** [comment]
Maybe, but the error is in the same place when using Graphhopper too, which makes me think it's probably something to do with the underlying data (which I've hopefully now fixed in OSM)

screenshot_20180216-173436

**Comment by ghoshkaj** [comment]
It looks like this PR is out of sync with master rn though. Rebase and merge? 😄

**Pull request merged**
