### PR TITLE
Attempt to cross-compile for arm64 Linux

### PR DESCRIPTION
**Pull request by SiarheiFedartsou**
# Issue
closes https://github.com/Project-OSRM/osrm-backend/issues/6405
## Tasklist

 - [ ] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md))
 - [ ] review
 - [ ] adjust for comments
 - [ ] cherry pick to release branch

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by mjjbell** [comment]
This appears to have generated a public package: https://github.com/Project-OSRM/osrm-backend/pkgs/container/osrm-backend%2Frun-on-arch-project-osrm-osrm-backend-osrm-backend-ci-aarch64-ubuntu20-04

Was that the intention? The package containers are already [providing ARM images](https://github.com/Project-OSRM/osrm-backend/pkgs/container/osrm-backend).

Usually it's safer to test these CI changes in a personal fork until they're ready.

**Comment by SiarheiFedartsou** [comment]
> This appears to have generated a public package: https://github.com/Project-OSRM/osrm-backend/pkgs/container/osrm-backend%2Frun-on-arch-project-osrm-osrm-backend-osrm-backend-ci-aarch64-ubuntu20-04
> 
> Was that the intention? The package containers are already [providing ARM images](https://github.com/Project-OSRM/osrm-backend/pkgs/container/osrm-backend).
> 
> Usually it's safer to test these CI changes in a personal fork until they're ready.

Oops, it likely was generated by https://github.com/uraimo/run-on-arch-action I was trying here. Will you be able to remove it please? I don’t have permissions for that it seems. 
It was successful attempt btw, but took >3h to compile OSRM from scratch(it is QEMU emulation), i.e. probably we shouldn’t go this way.

**Comment by mjjbell** [comment]
> Oops, it likely was generated by https://github.com/uraimo/run-on-arch-action I was trying here. Will you be able to remove it please? I don’t have permissions for that it seems. 

@DennisOSRM would you mind deleting this package? https://github.com/Project-OSRM/osrm-backend/pkgs/container/osrm-backend%2Frun-on-arch-project-osrm-osrm-backend-osrm-backend-ci-aarch64-ubuntu20-04

> It was successful attempt btw, but took >3h to compile OSRM from scratch(it is QEMU emulation), i.e. probably we shouldn’t go this way.

Yes, the current container building action is using QEMU and is also [very slow](https://github.com/Project-OSRM/osrm-backend/actions/runs/3251420321).  Even though it only runs on releases, finding a faster alternative would be worthwhile IMO.

**Comment by SiarheiFedartsou** [comment]
> Even though it only runs on releases, finding a faster alternative would be worthwhile IMO.

AFAIK when it comes to Docker images the only alternative is to build on ARM machine.

**Comment by DennisOSRM** [comment]
> @DennisOSRM would you mind deleting this package? https://github.com/Project-OSRM/osrm-backend/pkgs/container/osrm-backend%2Frun-on-arch-project-osrm-osrm-backend-osrm-backend-ci-aarch64-ubuntu20-04

Will be looking into it later tonight.

**Comment by DennisOSRM** [comment]
> > Even though it only runs on releases, finding a faster alternative would be worthwhile IMO.
> 
> 
> 
> AFAIK when it comes to Docker images the only alternative is to build on ARM machine.

There's an ARM server with an actions runner already installed that I could provide.

**Comment by SiarheiFedartsou** [comment]
> > > Even though it only runs on releases, finding a faster alternative would be worthwhile IMO.
> > 
> > 
> > AFAIK when it comes to Docker images the only alternative is to build on ARM machine.
> 
> There's an ARM server with an actions runner already installed that I could provide.

After playing for a couple of hours with QEMU and cross compilation I can say that(it is mainly about node-osrm, not Docker image):
1. QEMU works, but it is super slow
2. Cross compilation it seems possible to configure, but I faced a couple of problems(in particular with TBB) which I am not sure how to solve and how much time it would take to finish with it.


So if it won’t bother you a lot it would be great to have access to this ARM server here(initially I thought that cross compilation will be simpler). Thanks!

**Comment by DennisOSRM** [comment]
> > @DennisOSRM would you mind deleting this package? https://github.com/Project-OSRM/osrm-backend/pkgs/container/osrm-backend%2Frun-on-arch-project-osrm-osrm-backend-osrm-backend-ci-aarch64-ubuntu20-04
> 
> Will be looking into it later tonight.

It' gone.

**Pull request closed without merging**
