### PR TITLE
Contractor: log stats for loaded speed files

### PR DESCRIPTION
**Pull request by freenerd**
Fixes https://github.com/Project-OSRM/osrm-backend/issues/2434

Output looks like this:

```
[info] Opening /tmp/extract.osrm.ebg
[info] Reading 702 edges from the edge based graph
[info] Loaded speed file /tmp/speeds.csv with 2 speeds
[info] In total loaded 1 speed file(s) with a total of 2 unique values
[info] Used 3382 speeds from LUA profile or input map
[info] Used 2 speeds from /tmp/speeds.csv
```

Todo:

- [x] Figure out what the high number in speeds from LUA profile means (one way streets are a thing)
- [ ] Code review

### CODE REVIEW

**Comment by TheMarex** [comment]
@freenerd build is failing on travis. Seems like you forgot to include `atomic` somewhere.

**Comment by daniel-j-h** [comment]
For the record: https://gcc.gnu.org/ml/libstdc++/2015-01/msg00121.html
We need to workaround GCC 4.8's `libstdc++` not defining `atomic_init`.

**Comment by daniel-j-h** [comment]
@freenerd if you want to use relaxed memory orders:
https://github.com/Project-OSRM/osrm-backend/pull/2440/commits/08f3a0b70df666a1bd10e499c4738a21760a0139#diff-5d25f965a92c5af3a4dfd03cf4f7616aR501
then it would make sense to `fetch_add` for incrementing the counters with relaxed instead of `+= 1`:
http://en.cppreference.com/w/cpp/atomic/atomic/fetch_add

**Comment by freenerd** [comment]
@daniel-j-h using `std::memory_order_seq_cst` which should work okay?

**Comment by daniel-j-h** [comment]
`store(0);` for initialization is good enough, as `store` has sequential consistency as default second argument already: http://en.cppreference.com/w/cpp/atomic/atomic/store

**Pull request merged**
