### PR TITLE
Updating extent of Hong Kong in list of left-hand drive countries

### PR DESCRIPTION
**Pull request by leighghunt**
Might be a little rough around Sha Tau Kok

#5535

## Tasklist

 - [x] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md)
 - [ ] review
 - [ ] adjust for comments
 - [ ] cherry pick to release branch

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by danpat** [comment]
@leighghunt This file was originally sourced from the iD editor - https://github.com/openstreetmap/iD/blob/master/data/drive-left.json

Can you check it that file has these corrections?  I noticed the other day that OSRM's version is also missing a few places like Samoa (which switched driving sides in 2009).

It'd be great to just stay in sync with iD and not maintain a fork of that file with tweaks.

**Comment by leighghunt** [comment]
Great - it already has Hong Kong corrected, but I've added Samoa and a few other islands in the Pacific, and Seychelles - once that's been reviewed, I'll resubmit with the updated data.

https://github.com/openstreetmap/iD/pull/6827

**Comment by leighghunt** [comment]
Hi @danpat, my changes to iD have been accepted, so I've brought them across here - note that a number of "deletions" that appear in my edit are actually moved over to the other side of the dateline - e.g. Kiribati, Samoa, etc.

I also just noticed that in doing so, I removed the following property from the features - do you need this?

```
 "driving_side": "left"
```

**Comment by leighghunt** [comment]
P.S. One other removal was the South Orkney Islands, which as far as I can tell have no roads. I couldn't find any reference to driving on the left hand side there - only South Georgia and the South Sandwich Islands to the North.

**Comment by leighghunt** [comment]
Hi again @danpat, just pinging you in case this got missed - I updated the iD version and have copied over here. Let me know if you have any further feedback.

Cheers.

**Comment by akashihi** [comment]
@leighghunt Looks like ID dropped that file completely on Nov 8, 2019  :(

Could you please resolve the conflict and update the dile, if applicable, so i'll merge it.

**Comment by leighghunt** [comment]
@akashihi conflicts should be sorted - let me know if you need me to do anything else. Cheers.

**Review by akashihi — APPROVED** [review]

**Pull request merged**
