### PR TITLE
Makes Cucumber Output Pretty

### PR DESCRIPTION
**Pull request by daniel-j-h**
Turns out I've never seen the pretty cucumber tests scroll by on my machine! The default format should be `pretty` but apparently it is not. I checked to make sure I'm using the bundled cucumber version.

https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#formats

This changeset hard-coded the pretty flag.

What I was seeing before for passing tests: dots.

cc @willwhite @MoKob 

```
Node Version v4.4.7
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
.....................................................................................................................................................................................................................
```

### CODE REVIEW

**Comment by emiltin** [comment]
the format was chosen to avoid overly long log files at the CI server. if a test fails, it will show it the full/prettty format. when running tests locally you can use the default profile which uses the pretty format.

by the way, the "-p verify" profile is defined in cucumber.js and uses --format progress. in case we want to use the pretty format at the CI server, i think we should not combine -p verify and with -f pretty which is confusing, but just instead just use a different profile (like default)

**Comment by emiltin** [comment]
in other words, when i run test locally i just do this and get the pretty format:
```
./node_modules/cucumber/bin/cucumber.js features/
```

**Comment by oxidase** [comment]
another argument for dots: full output slows down tests. it is acceptable for local terminals, but running tests remotely via ssh is will be terrible. As a compromise could be a second command for npm with `--format=pretty`

**Comment by daniel-j-h** [comment]
Good points - will close here.

But why is it some people seem to have the pretty format on by default (as advertised)? I know @MoKob at least does have the pretty format.

**Comment by emiltin** [comment]
what command do you use to run tests locally?

**Comment by daniel-j-h** [comment]
`npm test`

and

`cucumber path/to/specific.feature`

**Comment by emiltin** [comment]
you could try adding "--format pretty" to the default profile in cucumber.js. if that helps. it doesn't specify any format, maybe that's why it ends up different for different people?

**Pull request closed without merging**
