### PR TITLE
Remove force flags and update extract/contract hashes with arguments

### LINKED ISSUE #2448: Caching test data in test/cache/ does not appear to speed up test runs
Seing no benefit to the caches created in test/cache/ when running on OS X. Will dig into this to see why...

```
$ rm -rf test/cache/ && time npm test && time npm test

> osrm-backend-test-suite@0.0.0 test /Users/dane/projects/osrm-backend
> npm run lint && ./node_modules/cucumber/bin/cucumber.js features/ -p verify


> osrm-backend-test-suite@0.0.0 lint /Users/dane/projects/osrm-backend
> eslint -c ./.eslintrc features/step_definitions/ features/support/

Node Version v4.4.3
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

597 scenarios (597 passed)
2656 steps (2656 passed)
3m04.020s

real	3m7.674s
user	1m39.314s
sys	1m54.104s

> osrm-backend-test-suite@0.0.0 test /Users/dane/projects/osrm-backend
> npm run lint && ./node_modules/cucumber/bin/cucumber.js features/ -p verify


> osrm-backend-test-suite@0.0.0 lint /Users/dane/projects/osrm-backend
> eslint -c ./.eslintrc features/step_definitions/ features/support/

Node Version v4.4.3
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

597 scenarios (597 passed)
2656 steps (2656 passed)
3m01.565s

real	3m5.500s
user	1m38.083s
sys	1m53.784s
```

### PR DESCRIPTION
**Pull request by oxidase**
Hi, PR must fix #2448. The problem is that force flags are undefined for the first feature and set for the rest, so cached files were forced to update.

### CODE REVIEW

**Comment by TheMarex** [comment]
Great find (again).

This is failing because the same osm files are extracted/contracted with different parameters but that is not included in the checksum. The approach that you chose is just to force a regeneration of the files.

We should address this problem by basing the checksum for the extracted/contraced also on the flags. I have a PR in the works for this.

**Comment by oxidase** [comment]
@TheMarex ok, i have included arguments in hashes for extract and contract. Now hashes are:
* fingerprintExtract = sha1(sha1(sha1(sha1(luaLibHash + binExtractHash) + profileHash) + extract args if any) + raster data if any)
* fingerprintContract = sha1(sha1(sha1(binContractHash) + contract args if any) + speed or turn penalties files if any) 

I also adjusted `reprocess` - now it starts extracting/contracting if not contracted. This fixes some issues with renaming extracted files in the first run but required for the next contractions with different fingerprintContract and the same fingerprintExtract.

With the commit for `rm test/cache ; npm test ; npm test`
```
...
598 scenarios (598 passed)
2666 steps (2666 passed)
1m51.576s
...
598 scenarios (598 passed)
2666 steps (2666 passed)
0m16.292s
```

**Comment by TheMarex** [comment]
@oxidase wow great work! Can you rebase so we can merge this?

**Comment by oxidase** [comment]
@TheMarex rebased, also sorted file extensions for easier check of new file extensions

**Pull request merged**
