### PR TITLE
Add feature name to vector tiles

### PR DESCRIPTION
**Pull request by vkurchatkin**

### CODE REVIEW

**Comment by TheMarex** [comment]
@danpat do you think this makes sense w.r.t. to vector tile size?

**Comment by vkurchatkin** [comment]
@TheMarex it probably makes sense to include names only on larger zoom levels

**Comment by danpat** [comment]
I think this is probably better achieved by using a separate basemap layer from a regular tileserver.  The debug tiles are really just to expose OSRM-internal data that's not available elsewhere (speeds, durations, turn costs, etc).  This is what the debug map at http://map.project-osrm.org/debug/ does, it allows plenty of context.

The tiles are already pretty heavy - adding name data to every single segment will only make that worse.  Additionally, the way the geometries are segmented means that label placement will be really terrible - labels won't follow curves, and there will be lots of collisions leading to pretty random label appearance.

@vkurchatkin Thanks for the contribution, but I think we'll hold off on this change for the moment.

**Comment by vkurchatkin** [comment]
@danpat thanks for the feedback!

>  The debug tiles are really just to expose OSRM-internal data that's not available elsewhere (speeds, durations, turn costs, etc).

Name is kind of internal, because it can be changed in profile script. I was trying to use it to attach  some data (way id, for example) and needed a way to visualize.

> the way the geometries are segmented means that label placement will be really terrible

Probably true, I've tried only to access it programmatically on mouse events.

**Comment by danpat** [comment]
@vkurchatkin ah, I see, hmm, interesting use-case.

With that in mind, I'm 👍  on this change.  Merging now :-)

**Pull request merged**
