### PR TITLE
Second Round Unit Tests for v5

### PR DESCRIPTION
**Pull request by daniel-j-h**
for https://github.com/Project-OSRM/osrm-backend/issues/2141.

### CODE REVIEW

**Comment by daniel-j-h** [comment]
The latest Trip unit test revealed an error in the v5 spec:

https://github.com/Project-OSRM/osrm-backend/pull/2246/commits/1a85987ace80e429ce58e41aba74149f5e871c7f#diff-696c8b82f14f945faf33258ed379f597R56

It is `waypoint_index` and not `position_index`. I already updated the Wiki. We should post that in the next rc / release announcement mail. /cc @TheMarex

**Comment by daniel-j-h** [comment]
Rebased against develop, incorporating amonst other changes the last uturn bikesh^Wrenaming.

**Comment by TheMarex** [comment]
@daniel-j-h what is missing here? Tests are still failing. :-/

**Comment by daniel-j-h** [comment]
Travis is failing because of this

    ./unit_tests/server-tests
    /home/travis/build.sh: line 45: ./unit_tests/server-tests: No such file or directory

    The command "./unit_tests/server-tests" exited with 127.

**Comment by BergWerkGIS** [comment]
Windows builds seem to be failing because of something else:

https://ci.appveyor.com/project/TheMarex/osrm-backend/build/1.0.1512#L3187

```
C:\projects\osrm\unit_tests\server\parameters_parser.cpp(204): error C2039: 'uturns': is not a member of 'osrm::engine::api::RouteParameters'
```

Going to take a look in a few.

**Comment by daniel-j-h** [comment]
Argh I fscked up the rebase, resolved in https://github.com/Project-OSRM/osrm-backend/pull/2246/commits/8ee8e41e419a5fd8311d48fe65088e7d66843369.

**Pull request merged**
