### PR TITLE
Coverage-based Fuzz Testing

### PR DESCRIPTION
**Pull request by daniel-j-h**
Follow up from https://github.com/Project-OSRM/osrm-backend/pull/2251, PR against master.

### CODE REVIEW

**Comment by TheMarex** [comment]
Totally forgot about this sorry. This seems good to merge, right?

Do you have any other suggestions of what should be fuzzed?

**Comment by daniel-j-h** [comment]
Hm I primarily started with the parsers since I was working on tests for them anyway.

I found a few string algorithms in util, but haven't had a deeper look. Perfect for this is side-effect free code with complex internal logic, e.g.

- [ ] Polyline encoder
- [ ] Base64 encoder
- [ ] Douglas Peucker
- [ ] Hilbert space filling curve

just to name a few off the top of my head.

**Comment by TheMarex** [comment]
Great. Can you ticket those? I'm going to merge this and enable on travis.

**Comment by daniel-j-h** [comment]
Done, breaking out into https://github.com/Project-OSRM/osrm-backend/issues/2370.

**Comment by daniel-j-h** [comment]
Docs! https://github.com/Project-OSRM/osrm-backend/blob/fuzz-all-the-things/docs/fuzzing.md

- [ ] we have to build `libFuzzer.a` on Travis **if** we want to run the fuzzers there

**Comment by daniel-j-h** [comment]
- [ ] add guide to `docs/testing.md` https://github.com/Project-OSRM/osrm-backend/pull/2497#issuecomment-224244330

**Comment by TheMarex** [comment]
Since this will never build on travis (no clang source for libfuzzer) and it would probably take too long we can't enable it for now. Fuzzing needs to be run locally.

**Pull request merged**
