### PR TITLE
[WIP] sudoless build on trusty

### PR DESCRIPTION
**Pull request by springmeyer**
Testing branch for how our builds work on the new trusty images: https://blog.travis-ci.com/2016-11-08-trusty-container-public-beta/

### CODE REVIEW

**Comment by springmeyer** [comment]
Currently broken with:

```
Disallowing packages: libstdc\+\+-5-dev, libstxxl-dev, libstxxl1, libzip-dev, lua5.1, liblua5.1-0-dev, libtbb-dev, libgdal-dev, libluabind-dev
If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
```

Starting with request for libstdc++-5 at https://github.com/travis-ci/apt-package-whitelist/issues/3597

**Comment by oxidase** [comment]
@springmeyer for asan builds binutils 2.26 is required with some bug fixes for
```
[100%] Linking CXX executable osrm-example
/usr/bin/ld: unrecognized option '--push-state'
``

 I did not find a better way than add ppa:jonathonf/binutils via sudo that provides 2.26 binutils for trusty. Once it will be in the whitelist than before_install.x86_64-asan.sh can be removed.

**Comment by springmeyer** [comment]
@oxidase - thank you for alerting me of the `sudo` usage inside the scripts at https://github.com/Project-OSRM/osrm-backend/blob/master/scripts/travis/. No action needed on your part: getting support for building on `sudo:false` boxes is not urgent. I propose we wait for travis to add whitelist support for the basic packages and then we can revisit this PR.

**Comment by daniel-j-h** [comment]
Just issues a Travis whitelisting request: https://github.com/travis-ci/apt-source-whitelist/issues/335

**Comment by springmeyer** [comment]
> Just issues a Travis whitelisting request: travis-ci/apt-source-whitelist#335

@daniel-j-h FWIW, binutils 2.27 is available via mason for linux: https://github.com/mapbox/mason/tree/master/scripts/binutils/2.27. Example using it for -flto: https://github.com/mapbox/vector-tile/blob/bench/.travis.yml#L48-L56

**Comment by daniel-j-h** [comment]
Interesting - so what's blocking your sudoless PR here?

**Comment by springmeyer** [comment]
> Interesting - so what's blocking your sudoless PR here?

@daniel-j-h whitelist for libstdc++-5-dev: https://github.com/Project-OSRM/osrm-backend/pull/3280#issuecomment-259799811.

Note: this PR is trying to test building sudoless on trusty. If we want to run sudoless on precise this PR would not be blocked by travis-ci/apt-package-whitelist#3597.

**Comment by daniel-j-h** [comment]
Closing - @TheMarex tested this in https://github.com/Project-OSRM/osrm-backend/pull/3852

**Pull request closed without merging**
