### PR TITLE
NodeJs based Http Server

### LINKED ISSUE #3832: Reimplement `osrm-routed` in NodeJS
Right now we are shipping our own implementation of:

- HTTP request parser
- async HTTP server
- URL parser (including a bunch of grammars for every API)

We can get rid of most of the `server/` folder by moving the code to NodeJS which already ships with production quality modules for all of this. After #3768 lands we would not induce a weird cyclic dependency anymore and this becomes feasible.

We should be able to replace most of the `boost::spirit` code with https://pegjs.org/.

Having this as node-express based tool would also enable us to easily integrate `osrm-text-instructions` and simplify hooking middle ware like authentication services into this.

### PR DESCRIPTION
**Pull request by daniel-j-h**
Resolves #3832.

## Tasklist
 - [ ] Url parses, grammars
 - [ ] Hook up node-osrm bindings
 - [ ] Switch Cucumber tests to using this
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] Battle test this
 - [ ] review
 - [ ] adjust for comments

### CODE REVIEW

**Comment by daniel-j-h** [comment]
Stale. This is not specced out and feedback wrt. consolidating our internal server never happened.

**Comment by emiltin** [comment]
hmm. still sounds like a good idea, if the recommended way to run osm in production is node, not osrm-routed?

**Comment by daniel-j-h** [comment]
Yes and that's why the issue is still open. I just closed this pull request since nothing was moving on that front and I don't want to keep it around in that state.

Switching osrm-routed to a Node.js based server and away from the crufty C++ HTTP server is still on the todo list just not a priority for us atm since we already do have a functioning HTTP server on top of node-osrm. Would require more coordination with our internal API (cc @freenerd @miccolis).

**Comment by emiltin** [comment]
i see, makes sense

**Pull request closed without merging**
