### PR TITLE
Vector tile plugin

### PR DESCRIPTION
**Pull request by danpat**
This PR is to address #1953, which started as a crazy idea, and then turned out to be not all that difficult to get working.

It adds:

   - a bounding-box search in the StaticRTree
   - a new `tile` plugin that will serve vector tiles at the `/tile?z={z}&x={x}&y={y}` URI

It's mostly clean, except for how the PBF is actually rendered by `osrm-routed`.  I had to add a special-case kludge in `request_handler.hpp` to render the `pbf` JSON part directly to the response stream, rather than going through one of the existing renderers.  I'm open to ideas on how to make this cleaner, but there's a built-in assumption that plugins will return JSON, and this plugin breaks that assumption.

The included `viewer.html` file is added to the repository root, but needs a better home.

Other notes:

   - `protozero` in `third_party/libosmium` was updated to include proper PBF write support
   - a new Buffer type was added to util::json so that downstream `node-osrm` can recognize string vs byte objects and render them directl

Known problems:

  - should probably implement limits on what zoom levels are honored, or cap the number if items returned in an RTree search - a tile that covers the whole USA would be....large
  - line-clipping hasn't been implemented, so long lines that make it a long way past the edges of the tiles sometimes experience a coordinate overflow and go off in strange directions.  This is most noticable at maximum zooms.
   - this plugin currently displays the `forward/reverse_weight` from the `EdgeBasedNodes` in the `StaticRTree`.  As per https://github.com/Project-OSRM/osrm-backend/issues/1857, these values are stale after traffic updates, so this plugin will need to be updated in line with the work done in https://github.com/Project-OSRM/osrm-backend/tree/dynamic_offset_calc
   - there are currently no tests
   - it would be nice to expose more data points, like turn costs (idea: once `dynamic_offset_calc` lands, turn costs are edge-based-node weight minus sum of segment weights (maybe, although last segment may have turn cost included, should it?)...

Please review.  I'm offline from Feb 20 to Feb 27, but I'd like to polish this and merge it when I get back, as i think we'll find it super useful.

### CODE REVIEW

**Comment by willwhite** [comment]
What's next for getting this merged? I think there are two options:

- Merge into develop and then port the changes to https://github.com/Project-OSRM/osrm-backend/pull/1935
- Just rebase against 5.0 now and PR against https://github.com/Project-OSRM/osrm-backend/pull/1935

**Comment by daniel-j-h** [comment]
There's a token in it, remove it and take care of it.

**Comment by TheMarex** [comment]
> Merge into develop and then port the changes to #1935

I would like to do this as it means we have a stepping stone on the old API. This branch needs a proper cleanup first:

- [ ] Remove all the HTML debugging stuff
- [ ] Quick code review by @daniel-j-h
- [ ] Quick code review by @TheMarex

Some thoughts:
- Extention through `json::Buffer` is ugly but in the old architecture not avoidable

@daniel-j-h can you look into getting this merged? It seems like it also breaks the tests.

After this in `develop` I will rebase the 5.0 API to include this plugin.

**Comment by alexshires** [comment]
Hi all,

I'm working on a osrm based project and have just discovered the recently added DEBUG_GEOMETRY option, which is very useful for our use case. However, from following your recent commits, you seem to plan to remove it in order to go straight to the final viewing option for debugging. Would it be possible to keep the debugging geojson output available please, and if so, can I do anything to help the development of this?

Regards,

Alex

**Comment by daniel-j-h** [comment]
@TheMarex this needs some more work before merging.

In particular patching third_party/libosmium for protozero changes is ugly, and I would rather pull in the latest libosmium release. Doing this next. Will then refactor the code a bit.

Should we put the debug-viewer into a separate repository in the Project-OSRM organization? Or even incorporate this in the frontend in some optional way?

**Comment by willwhite** [comment]
@daniel-j-h I rebased this on the `develop` branch to make sure 69bc8a8b2214da798ffd39f6ebd98d82a1bf5103 was included here. Just a heads up in case you start cleaning this up in the morning.

**Comment by TheMarex** [comment]
@alexshires Yes this will replace the geojson output as it just does not scale over trivial data set sizes. Decoding vector tiles should not be too hard - also its easier to visualize as it requires no intermediate step.

**Comment by alexshires** [comment]
@TheMarex thanks, no problem, I'd have liked to keep it for small enough datasets but we'll try and convert OSM to our own formatting.

**Comment by daniel-j-h** [comment]
- [ ] decide where to put `debug-viewer` and pull it out of the Git history
- [ ] there's still duplicate code in `tile.hpp`, refactor it if possible
- [ ] use portable math constants as we do in the whole code base
- [ ] where is the c&p code from? at least mapnik and somewhere else? are there license issues?
- [ ] `Buffer` is a string containing bytes (what about `\0`?) that we escape and put out as JSON? Wat?
- [ ] there are lines simply commented out in the changes which I do not understand; clarify
- [ ] there are todos in the code, e.g. templating `RectangleInt2D`; want to do this?

**Comment by daniel-j-h** [comment]
Seeing a few issues on the Travis OSX instances wrt. `bind<void>`. Let's see if switching to the latest XCode helps as @MoKob reported. If this works out, I'm handing this back to @danpat.

**Comment by TheMarex** [comment]
Test passed, and rebased on develop, merging. :+1:

**Comment by willwhite** [comment]
:clap:

**Pull request merged**
