### PR TITLE
Refactor and document contractor

### PR DESCRIPTION
**Pull request by TheMarex**
Todo:
- [x] Move options code into own class like for extractor
- [x] More documentation for the EdgeBasedGraphFactory
- [x] Refactor extractor_containers::Prepare()
- [x] Move edge de-duplication into extractor
- [x] Trim down the number of different edge types
- [x] Test on big dataset

### CODE REVIEW

**Comment by TheMarex** [comment]
@chaupow your checklist (can be found [here](https://github.com/Project-OSRM/osrm-backend/wiki/Code-Review)):

- [ ] Rebased on develop
- [ ] Formated using `clang-format`
- [ ] Code uses the estabilished naming convention:
  - Methode names are CapitalCamelCase
  - Function names are camelCase
  - Variable and attribute names use under_score
  - Namespaces use under_score
  - std-like util functions use std-like style
- [ ] Is everything that could be const declared as const?
  - Methodes
  - Variables
- [ ] Is `auto` used whenever possible?
- [ ] General structure:
  - Do the methodes make sense to you?
  - Can the control flow be easily interfered?
- [ ] Documentation
  - Is the behaviour of important functions documented?
  - Is the idea of important classes documented?
  - If the algorithm is based on a specific paper: Is there a citation?
- [ ] Are there enough assertions?
  - Are indices calculations checked by assertions?
  - Is external data (e.g. read from disk) checked by assertions?
  - Are important assumptions checked by assertions?
- [ ] Tests
  - Do the tests pass?
  - In case of new functionality: Where tests added?
  - Do you see parts that could be better tested by Unit tests?

**Comment by chaupow** [comment]
@TheMarex I'll start looking into this tomorrow. Any tips on how to do this the best way? Is there a write up or a small diagram what the classes in contractor do and how they are related to each other? :D 

Otherwise my plan would be to 
1) skim through the classes in /contractor/*
2) go through all diffs in "Files changed" of this PR in detail.

**Comment by TheMarex** [comment]
@chaupow the most efficient way to do this is looking at the PR diff and checking out the branch locally so you can compile and test.

> Is there a write up or a small diagram what the classes in contractor do and how they are related to each other?

Hah. I'm afraid not. I tried to make a dent by adding some documentation for context, but feel free to poke me if something is unclear.

**Comment by emiltin** [comment]
i once wrote a explanation of the processing flow at https://github.com/Project-OSRM/osrm-backend/wiki/Processing-Flow. it's becoming increasingly outdated but perhaps it could stil be of some use.

**Comment by TheMarex** [comment]
@emiltin thanks for the link, I'm going to update that if I find some spare time this week.

**Comment by chaupow** [comment]
@emiltin thanks for the link. I started looking into the extractor yesterday and it helped a lot. I'll try updating in case I find something :)

**Comment by TheMarex** [comment]
@chaupow let's hold on the review for now. Had to do some bigger changes, need to clean this up again first.

**Comment by TheMarex** [comment]
This PR has become a little unwieldy, I'm going to split it into smaller chunks.

**Comment by TheMarex** [comment]
First chunk here https://github.com/Project-OSRM/osrm-backend/pull/1501

**Pull request merged**
