### PR TITLE
Stop signs for the turn function in lua profiles

### PR DESCRIPTION
**Pull request by chaupow**
# Issue

Implementing https://github.com/Project-OSRM/osrm-backend/issues/2652

## Tasklist
 - [ ] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] add regression / cucumber cases (see docs/testing.md)
 - [ ] review
 - [ ] adjust for comments

### CODE REVIEW

**Comment by SiarheiFedartsou** [comment]
@mjjbell what do you think about it? Should we finish it?

**Comment by mjjbell** [comment]
Yes I think it's worth doing.

I remember reading this when implementing the traffic signal directions in  #6153
It seems similar in that you need to know in the direction of approach to the node, so if this PR it too out-of-date, we could try and reuse that to implement it.

**Comment by mjjbell** [comment]
These changes look very similar to what I did for traffic signals, but they didn't make it to master: https://github.com/Project-OSRM/osrm-backend/commit/d1b9dffdd10652a35347f77a59ac5c765be95d51

**Comment by SiarheiFedartsou** [comment]
> Yes I think it's worth doing.

We should probably decide what to do with https://github.com/Project-OSRM/osrm-backend/pull/6354 then - I would expect quite a lot of merge conflicts if do this in current code base and then try to merge #6354

**Comment by mjjbell** [comment]
Ok, I'll take a look soon.

**Comment by DennisOSRM** [comment]
closing stale PR. Reopen if still relevant.

**Pull request closed without merging**
