### PR TITLE
prefer ways on route=bicycle

### LINKED ISSUE #5032: prefer ways with bicycle routes
in bicycle routing, prefer ways that are a part of a `route=bicycle` relation by changing forward/backward rate by a factor of 1.1. Currently it's used by https://github.com/FreemapSlovakia/freemap-routing

Implementation:
**Add this function:**
```(lua)
function get_from_rel(relations, way, key, value, ret)
        -- if any of way's relation have key=value, return tag ret; else return nil
        local rel_id_list = relations:get_relations(way)
        for i, rel_id in ipairs(rel_id_list) do
                local rel = relations:relation(rel_id);
                local p = rel:get_value_by_key(key);
                if value == '*' and p then return rel:get_value_by_key(ret); end
                if p == value then return rel:get_value_by_key(ret); end
        end
        return nil;
end
```
**Create handler**
```(lua)
function WayHandlers.cyclerelation(profile,way,result,data, relations)
    local is_route = get_from_rel(relations, way, "route", 'bicycle', "route");
    if result.forward_rate and is_route then
         result.forward_rate = result.forward_rate *1.1
    end
    if result.backward_rate and is_route then
         result.backward_rate = result.backward_rate *1.1
    end
end
```
and run this handler.

@chaupow @emiltin  what do you think?

### PR DESCRIPTION
**Pull request by MichalPP**
# Issue

change forward/backward rate on ways, that are a part of route=bicycle. fix  #5032

### CODE REVIEW

**Comment by MichalPP** [comment]
@chaupow how do I ask travis/appveyor to run the checks again? (half of them were run before I included the third commit)

**Comment by TheMarex** [comment]
@MichalPP hrm they should re-run after every commit. Looks like some failed. Do they work for you locally?

**Comment by chaupow** [comment]
Sorry somehow this slipped through my mailbox attention time span.

As @TheMarex pointed out seems they failed? 🤔 

But if you encounter this problem again, you can try pushing 
`git commit --allow-empty -m "Trigger travis"`

**Comment by MichalPP** [comment]
commit 2 and 3 should be just one commit (or 3 should be done before 2). 3 includes the function and 2 uses it.

(I haven't yet mastered git on command line)

**Comment by MichalPP** [comment]
closing in favour of https://github.com/Project-OSRM/osrm-backend/pull/5092 

my git knowledge is increasing every minute :)

**Pull request closed without merging**
