### PR TITLE
Lets MakeResponse(Route) explicitly call MakeResponse(ManyRoutes) in RouteAPI

### PR DESCRIPTION
**Pull request by daniel-j-h**
See https://github.com/Project-OSRM/osrm-backend/pull/4035#discussion_r116890340

### CODE REVIEW

**Comment by daniel-j-h** [comment]
Small self-contained example:

- clang https://godbolt.org/g/CJ6Pa7
- gcc https://godbolt.org/g/fIl2S5

**Comment by oxidase** [comment]
nice, it hits [the note](https://stackoverflow.com/questions/3592557/optimizing-away-a-while1-in-c0x)

> [ Note: This is intended to allow compiler transformations such as removal of empty loops, even when
termination cannot be proven. — end note ]

**Comment by danpat** [comment]
Yeah.  I think we avoided the problem through the following mechanism:

  1. Compiler optimized away `MakeResponse(Route)`
  2. Calls that would've matched `MakeResponse(Route)` were instead redirected to `MakeResponse(ManyRoutes)` because it can cast `Route`->`ManyRoutes`

While this works, it's definitely a bit black-magicy, removing this weird function is 👍

**Comment by daniel-j-h** [comment]
Follow up from chat: AppVeyor build was 🍏 looks like a spurious error:
https://ci.appveyor.com/project/DennisOSRM/osrm-backend/build/1.0.8186

Also: after meging this into master Travis also had a spurious failure:
https://travis-ci.org/Project-OSRM/osrm-backend/jobs/233549233

where we were unable to download Clang, silently continued the build, used the system's pre-installed Clang 3.5 and then errored during compilation.

```
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/linux-x86_64/clang++/4.0.0.tar.gz...
CMake Error at cmake/mason.cmake:80 (message):
[Mason] Failed to download  https://mason-binaries.s3.amazonaws.com/linux-x86_64/clang++/4.0.0.tar.gz:
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
```

**Pull request merged**
