### PR TITLE
New Travis CI integration

### PR DESCRIPTION
**Pull request by daniel-j-h**
Dummy pull request for trying out the new Travis CI integration. Details follow.

### CODE REVIEW

**Comment by daniel-j-h** [comment]
Blocked by:

- https://github.com/travis-ci/apt-package-whitelist/issues/1355
- https://github.com/travis-ci/apt-package-whitelist/issues/1356
- https://github.com/travis-ci/apt-package-whitelist/issues/1357
- https://github.com/travis-ci/apt-package-whitelist/issues/1358

**Comment by daniel-j-h** [comment]
Todo:

- [ ] wait for packages to be whitelisted
- [ ] builds for `-DBUILD_SHARED_LIBS=ON`

**Comment by daniel-j-h** [comment]
Now that the packages are whitelisted, it seems like the only problem is luabind depending on libboost from the default apt source, but we pull in boost 1.55 from the latest apt source.

**Comment by TheMarex** [comment]
@daniel-j-h we could try going on `14.04`:

http://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/

That should make boost new enough so we can use the vanilla packages.

**Comment by daniel-j-h** [comment]
I got rubygems on the whitelist. In Trusty they renamed it to rubygems-integration. Oh look:

> Disallowing packages: rubygems-integration
> If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process

...

**Comment by TheMarex** [comment]
:rocket:

**Pull request merged**
