### PR TITLE
Control release mode debug logging output by ENABLE_DEBUG_LOGGING option

### PR DESCRIPTION
**Pull request by wangyoucao577**
# Issue

What issue is this PR targeting? If there is no issue that addresses the problem, please open a corresponding issue and link it here.
https://github.com/Project-OSRM/osrm-backend/issues/3427

Please read our [documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/releasing.md) on release and version management.
If your PR is still work in progress please attach the relevant label.

## Tasklist

 - [x] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md)
 - [ ] review
 - [ ] adjust for comments
 - [ ] cherry pick to release branch

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by wangyoucao577** [comment]
As I write in https://github.com/Project-OSRM/osrm-backend/issues/3427#issuecomment-563284389, the performance of debug log is acceptable.

**Comment by akashihi** [comment]
Can it be a compile time option? So one will be able to choose, whether debug output should not be compiled at all in release mode, or compiled in but not visible by default?

**Comment by wangyoucao577** [comment]
> Can it be a compile time option? So one will be able to choose, whether debug output should not be compiled at all in release mode, or compiled in but not visible by default?

Technically it's ok to be a compile time option, actually the `NDEBUG` is already the one. However, is it really valuable to control it by compiling? Intutively people will expect to have the debug log simply by `-l DEBUG` at runtime, that what I was thought before really deep dive the code. It really made bothered me for a long time. So that I stronglly suggest to remove the compile time control.

**Comment by danpat** [comment]
I think whether performance is acceptable or not depents where the debug log output is being generated.  If someone places a debug message in one of the important loops during data processing, even if logging is suppressed, it could increase processing time.

My preference would be to leave the current behaviour by default - compile-time-disable debug logging, but may be add a CMake rule that *enables* debug logging for release builds if it's desired.

**Comment by wangyoucao577** [comment]
> I think whether performance is acceptable or not depents where the debug log output is being generated. If someone places a debug message in one of the important loops during data processing, even if logging is suppressed, it could increase processing time.
> 
> My preference would be to leave the current behaviour by default - compile-time-disable debug logging, but may be add a CMake rule that _enables_ debug logging for release builds if it's desired.

@danpat  I have added cmake option `ENABLE_DEBUG_LOGGING` as you suggested. Its behavior is very similar with `ENABLE_ASSERTIONS` that defaully `ON` in debug mode and `OFF` in release mode. With `-DENABLE_DEBUG_LOGGING=ON` it can be enabled in release mode also. Please help to review it. Thanks!

**Comment by akashihi** [comment]
Looks good for me!

@danpat @gardster Any objections to merge this?

**Pull request merged**
