### PR TITLE
Experimental version of tile plugin using vtzero.

### PR DESCRIPTION
**Pull request by joto**
This uses the new vtzero library (https://github.com/mapbox/vtzero)
instead of using protozero directly. The code becomes much cleaner this way and the generated tiles are smaller. Note that I have rewritten the code but only did a little bit of ad-hoc testing. To run this you'll need the newest release of protozero and vtzero master installed.

# Issue

#4685 

## Tasklist
 - [ ] ADD OWN TASKS HERE
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [x] add regression / cucumber cases (see docs/testing.md)
 - [ ] review
 - [ ] adjust for comments

## Requirements / Relations

Might need vendored in vtzero. The protozero vendered in with libosmium will need to be updated. Don't merge until there is an official released version of vtzero.

/cc @springmeyer

### CODE REVIEW

**Comment by springmeyer** [comment]
Thanks for getting this going @joto. I agree that this should wait to merge for an official vtzero release. At the same time, would be great if @danpat could find a moment to kick the tires on this to provide any feedback now that might help guide any needed changes in vtzero before official release.

**Comment by TheMarex** [comment]
Thanks this looks great, 300 LOC less 🎉 Looking forward to the vtzero release.

**Comment by oxidase** [comment]
@joto @danpat I have updated tile plugin unit tests. Please could you review the PR?

**Comment by oxidase** [comment]
@TheMarex debug tiles look good
screenshot from 2018-04-24 10-46-04

**Pull request merged**
