### PR TITLE
add a follow-up section on testing for guidance tests

### PR DESCRIPTION
**Pull request by MoKob**
# Issue

More a guide addition than an issue

## Tasklist
 - [x] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] review
 - [ ] adjust for comments

## Requirements / Relations
none

### CODE REVIEW

**Comment by daniel-j-h** [comment]
cc @chaupow @karenzshea could you have a look here

**Comment by MoKob** [comment]
Any feedback here, or can we just merge and update later if clarifications turn out to be necessary?

**Comment by karenzshea** [comment]
Looks great!

**Comment by MoKob** [comment]
So good to merge?

**Pull request merged**
