### PR TITLE
Avoid samelookup in heap map

### PR DESCRIPTION
**Pull request by xlaussel**
#5876

I did expose (made public) the HeapNode struct of the heap and add functions to access it directly instead of getting the NodeID.
This permits accessing the contained data (weight, data and handle) directly instead of making further calls to getKey or getData and so avoid other (same) lookup into the map.

I did modify the algorithms to use the new functions when relevant.
Accordingly, I did also some small changes to some call passing only the  HeapNode instead of the NodeID, weight and data.

I think this can speed-up the computation time but I have no big benchmark to test it.

The cucumber tests are OK.

## Tasklist

 - [ ] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md)
 - [ ] review
 - [ ] adjust for comments
 - [ ] cherry pick to release branch

### CODE REVIEW

**Comment by xlaussel** [comment]
Hi,

The travis build complains only about the format ( clang-format ) of one file. I did check this file and it is OK for me but I am using a newer version of clang-format (7.0.1) and I can't downgrade to 3.8. I think this is the reason of the problem. What can I do, waiting for the actual ongoing PR for clang-format upgrade?

**Comment by danpat** [comment]
I just merged https://github.com/Project-OSRM/osrm-backend/pull/5895 - you should pull from `master` and merge into your branch.  clang-format 10.x is now our baseline tool.

**Review by akashihi — CHANGES_REQUESTED** [review]
Is `package-lock.json` change really relevant for that PR? I assume it should only touch c++ code

**Comment by xlaussel** [comment]
> Is `package-lock.json` change really relevant for that PR? I assume it should only touch c++ code

Hi
Yes it was not on purpose. Corrected.

**Comment by xlaussel** [comment]
Hi,
I did revert the file to the master version and commited. The checks are OK but th merge has not been performed automatically as it should.Can you check?
Xavier Laussel06.10.10.64.69 

    Le dimanche 13 décembre 2020 à 22:10:33 UTC+1, Denis Chapligin <notifications@github.com> a écrit :  
 
 


@akashihi requested changes on this pull request.

Is package-lock.json change really relevant for that PR? I assume it should only touch c++ code

**Review by akashihi — APPROVED** [review]

**Comment by akashihi** [comment]
@xlaussel Merged and thank you for your contribution

**Pull request merged**
