### PR TITLE
Handle all distances between coordinates being zero in Farthest Insertion algorithm.

### PR DESCRIPTION
**Pull request by daniel-j-h**
Assertions for additional safety and sanity.

References:
- resolves https://github.com/Project-OSRM/osrm-backend/issues/2147 for v4

### CODE REVIEW

**Comment by daniel-j-h** [comment]
This no longer crashes routed. There is the possibility that we return "empty" trips as in
https://gist.github.com/daniel-j-h/a7de7e143b2a063805cbe95fe30aa1e3

Is this the expected behavior for Trip with e.g. two times the same coordinates (read: two locations that snap to the same coordinates)?

Note also I only worked on the Farthest Insertion algorithm, I have not yet looked at others. Should we ticket that up as potential problems? I don't feel like I want to spent a lot of time with this at the moment.

**Comment by daniel-j-h** [comment]
Also needs trivial v5 backport / cherry-pick when this is ready to be merged.

**Comment by daniel-j-h** [comment]
I'm also curious why I can not reproduce this on v5 --- did we change something in the snapping code? That is, the fix should definitely be backported to v5, the coordinates in the original issue just do not trigger the issue.

**Comment by TheMarex** [comment]
> did we change something in the snapping code?

In general yes, but I didn't remember that I had to pull this in the trip plugin as well.

Going to hold off merging here because I need to coordinate the merge with a rebase of `v5`. Most likely EOD.

**Pull request merged**
