### PR TITLE
Split build command into two layers

### PR DESCRIPTION
**Pull request by nurikk**
# Issue

This PR modifies dockerfile in order to split dependencies installation and sources compilation into separate docker layers, splitting enables caching for `apt-get update/install` command

Please read our [documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/releasing.md) on release and version management.
If your PR is still work in progress please attach the relevant label.

## Tasklist

 - [ ] CHANGELOG.md entry ([How to write a changelog entry](http://keepachangelog.com/en/1.0.0/#how))
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md)
 - [ ] review
 - [ ] adjust for comments
 - [ ] cherry pick to release branch

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by mjjbell** [comment]
@nurikk do you have any numbers on the change in container size with this change?

**Comment by hoerup** [comment]
This change doesnt matter since it only modifies the build stage which is discarded, and only runstage image is uploaded to the repo

**Comment by nurikk** [comment]
> This change doesnt matter since it only modifies the build stage which is discarded, and only runstage image is uploaded to the repo

This makes sense when you're building docker image locally

**Review by mjjbell — APPROVED** [review]
Thanks!

**Comment by mjjbell** [comment]
@nurikk can add an entry to `CHANGELOG.md` for this too.

**Comment by nurikk** [comment]
> @nurikk can you add an entry to `CHANGELOG.md` for this too.

done

**Pull request merged**
