### PR TITLE
Do not collapse away lane steps as long as they are necessary

### PR DESCRIPTION
**Pull request by daniel-j-h**
At the moment we collapse away `UseLane` steps when they are short, although they might have critical lane information associated with them. A use-case for this is https://github.com/Project-OSRM/osrm-backend/issues/2625 (during which this actually emerged) where multiple `UseLane` instructions potentially have to be looked at.

This changeset modifies collapsing steps by only collapsing `UseLane` if the lane information is redundant.

@MoKob this breaks two tests: one for pulled back lanes and one for uturn roads at intersection: an additional `UseLane` is introduced there. Would you be so kind to have a look at both, since I'm not sure about the behavior you expect there.

### CODE REVIEW

**Comment by MoKob** [comment]
I have a pretty good idea on what I have to do to make this work again. Will take this one over tomorrow.

**Comment by MoKob** [comment]
I have rebased this on advanced-lanes to not implement the necessary handling twice.

**Comment by TheMarex** [comment]
What is the state here? Ready to merge? This seems to need a rebase.

**Comment by MoKob** [comment]
Advanced Lane Stuff should wait until 5.4, since it changes a few high risk items that could easily introduce bugs.

**Comment by MoKob** [comment]
This one has been merged into https://github.com/Project-OSRM/osrm-backend/pull/2614. Closing here.

**Pull request closed without merging**
