### PR TITLE
Partially fix via-routing when vias are on the same way

### PR DESCRIPTION
**Pull request by danpat**
This small change partly addresses #1424, and does not seem to re-introduce #1429.

When two vias are placed on the same way (NodeID), it causes the reverse heap test (`WasInserted`) to return true in the first round call to `RoutingStep`.  When a previous leg has a distance offset in place, the loop thinks the two ends of the bi-directional Dijkstra search have met and no further edges are visited, the two vias are routed directly, even if the way is marked as one-way, and the vias are not visitable in their placed order.

This change adds an explicit test for vias on the same way.  When detected, the distance offset is not applied to the nodes inserted into the search heaps.  This leads to proper traversal of the edge graph.

One point of note:  the `raw_route_data.shortest_path_length` value is not correct, further changes are needed to make that bit work too.

Additionally, while the tests in `features/testbot/via.feature` address this bug specifically, I could not get them all to work.   Only two of the tests in the `Via points on ring on the same oneway` scenario work, the other three are returning no results to the test suite, although manual testing of these scenarios seems to work OK.  I'm not familiar enough with cucumber to dig all the way into it at this stage.

### CODE REVIEW

**Comment by TheMarex** [comment]
@danpat awesome work figuring this one out. Will start to review this now.

> One point of note: the raw_route_data.shortest_path_length value is not correct, further changes are needed to make that bit work too.

Hm, just subtracting the edge offsets from the overall distance should work. But I need to check that.

**Comment by danpat** [comment]
My gut tells me that this solution is a hack, and it should be possible to make it work more in-line with Dennis' original change, using the phantom node weights to get proper ordering.  However, my brain isn't quite grokking all the interactions and I couldn't come up with anything else that would work.

The source of the "weird" paths seen in #1429 is because when cumulative `distance1` and `distance2` are used, the post-loop swap here:

https://github.com/Project-OSRM/osrm-backend/blob/master/routing_algorithms/shortest_path.hpp#L314

is sometimes called incorrectly.

**Comment by TheMarex** [comment]
Hm, so the reason your fix works is, that it triggers [this condition](https://github.com/danpat/osrm-backend/blob/17dd39609f7325defbeecc2217804e0773cc0e76/routing_algorithms/routing_base.hpp#L81), so the `upper_bound` gets not set to 0 and we don't terminate the search.

If the street segment is actually bidirectional this should lead to incorrect results. Because we need to actually terminate at that position, right?

Regarding the cumulative `distance1` and `distance2` values, I think I get what he was trying to do:
- Dijkstra does not care which initial distance value the start node has: it is just an offset
- You want to get the overall shortest route, not just the shortest routes between two vias. But that depends on the current best distance to the forward and reverse node of the source
- But if you want to accumulate the `local_upper_bound`s (the distance between the vias) you can't offset the initial distance value, thus the removal

Ideas why Dennis fix is broken:
There is something that actually relies on `distance1` and `distance2` being the distance to the previous via's forward/reverse node. Maybe the wrong via leg is chosen?

**Comment by TheMarex** [comment]
In conclusion I think we should maybe start working from the original patch and exactly figure out why it is broken: That is try to construct a minimal lua test case. I still have an extract from Lierop which is mentioned here https://github.com/Project-OSRM/osrm-backend/issues/1429, maybe I can reduce the data in JOSM to a test case.

**Comment by danpat** [comment]
Agreed.  Now that I'm a bit more familiar with the cucumber test framework, I'll see if I can build a failing test.

**Comment by TheMarex** [comment]
@danpat This is a smaller extract from Lierop where you could try to find a test case for #1429 https://drive.google.com/file/d/0B0Q8fvc1VRlDNW9hVE5pd09xVzQ/view?usp=sharing

**Comment by emiltin** [comment]
note that you can load osm or pbf files from cucumber. that way you can start with an actual .osm extract, and reduce it in steps.

**Comment by TheMarex** [comment]
Closing in favor of new PR.

**Pull request closed without merging**
