### PR TITLE
Update to libosmium@2.9.0

### PR DESCRIPTION
**Pull request by karenzshea**
# Issue

https://github.com/Project-OSRM/osrm-backend/issues/2920

mapbox variant is still on 1.1.0

## Tasklist
 - [ ] review
 - [ ] adjust for for comments

## Requirements / Relations
needs https://github.com/Project-OSRM/osrm-backend/pull/2974

### CODE REVIEW

**Comment by daniel-j-h** [comment]
1/ https://travis-ci.org/Project-OSRM/osrm-backend/jobs/163856027#L4025 fails but works locally. @karenzshea this is your caching issue, correct?

2/ https://travis-ci.org/Project-OSRM/osrm-backend/jobs/163856029#L712 should be fixed with https://github.com/Project-OSRM/osrm-backend/pull/2974.

**Comment by karenzshea** [comment]
Test failures were due to a change in scientific notation parsing in libosmium 2.9.0. Ticketed at https://github.com/osmcode/libosmium/issues/165

**Comment by karenzshea** [comment]
Second set of failures were effects from https://github.com/Project-OSRM/osrm-backend/pull/2974, building with protozero in strict mode removed access to underlying iterator pairs.

**Comment by karenzshea** [comment]
idk what happened here 
https://github.com/Project-OSRM/osrm-backend/pull/2994

**Pull request closed without merging**
