### PR TITLE
Removes profiles from osrm-prepare, only needed in osrm-extract

### LINKED ISSUE #1950: lua profile not required for osrm-prepare
Now that the edge-based-graph generation happens in osrm-extract, we no longer need the lua profile for osrm-prepare.

We should remove the require parameters from the osrm-extract tool.

### PR DESCRIPTION
**Pull request by daniel-j-h**
Fixes #1950.

Toolchain is now

    osrm-extract -p profiles/car.lua finland-latest.osm.pbf
    osrm-prepare finland-latest.osrm

We need to

- [x] communicate this change to the users
- [x] adapt docs, wiki

### CODE REVIEW

**Comment by TheMarex** [comment]
- [ ] Adapt cucumber test to adhere to the new cmd-line options

Otherwise :+1:

**Comment by daniel-j-h** [comment]
Capturing from chat, rename `osrm-contract` while we're breaking things.

**Comment by daniel-j-h** [comment]
Updated Wiki, merge once Travis gives okay.

**Comment by daniel-j-h** [comment]
With the updated documentation in place we should merge this in soon (and coordinate with demo server). Already got a confused user today on IRC.

**Pull request merged**
