### PR TITLE
[EXPERIMENTAL] Supply additional name hint to guide coordinate snapping

### PR DESCRIPTION
**Pull request by danpat**
# Issue

This PR adds a name hint to help guide coordinate snapping.  If supplied as part of the request, coordinates will only snap to roads that are "similar" (to be defined) to the supplied name hint.

The new parameter is of the form `name_hint=main st;destination st`.  I'm still toying with the actual filtering/selection logic, suggestions welcome.

## Why?
Geocoders don't always return a coordinate that's ideal for routing purposes.  It's not always closest to the intended destination road.

A good example is this address:

http://www.openstreetmap.org/node/596865687

which you can search for with Nominatim as "4850 Edgeware Road".  The data is sourced from the San Diego GIS department and published as public domain data.

Unfortunately, OSRM snaps this coordinate to the alley behind the house, which is closer to the geocoded coordinate than Edgeware Road.

## Tasklist
 - [ ] Make matches case insensitive
 - [ ] Consider stripping prefix/suffix
 - [ ] Limit r-tree search when no nearby names match to avoid runaway searches
 - [ ] Avoid re-checking segments from the same named road that don't match
 - [ ] Finalize selection logic
 - [ ] Consider API/parameter naming
 - [ ] Implement for all `Nearest*` methods
 - [ ] Make hints optional for each coordinate (i.e. blank = no name filtering)
 - [ ] Benchmark
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] add regression / cucumber cases (see docs/testing.md)
 - [ ] review
 - [ ] adjust for comments

### CODE REVIEW

**Comment by emiltin** [comment]
some form of edit distance? https://en.wikipedia.org/wiki/Edit_distance

**Comment by Komzpa** [comment]
Please keep in mind ex-USSR block architecture, when there are a lot of unnamed passages inside.

http://map.project-osrm.org/?z=17&center=53.888261%2C27.686223&loc=53.891189%2C27.688218&loc=53.888223%2C27.684109&hl=en&alt=0


For instance, this:
http://map.project-osrm.org/?z=17&center=53.863227%2C27.611625&loc=53.866245%2C27.609962&loc=53.861613%2C27.610348&hl=en&alt=0

Sould not become this:
http://map.project-osrm.org/?z=18&center=53.863439%2C27.608535&loc=53.864372%2C27.611293&loc=53.863391%2C27.608932&hl=en&alt=0

**Comment by daniel-j-h** [comment]
@danpat is this still actionable or can we close?

**Comment by emiltin** [comment]
curious why this was abandoned?

**Comment by daniel-j-h** [comment]
Scope creep - we're not building a geocoder ;)

**Comment by emiltin** [comment]
ok makes sense!

**Comment by gardster** [comment]
I'm really want to have any instrument to handle cases like https://www.openstreetmap.org/way/265282556
http://map.project-osrm.org/?z=18&center=40.758225%2C-73.996798&loc=40.757676%2C-73.998080&loc=40.760293%2C-73.994390&hl=en&alt=0 Maybe you will use any other feature, like osm_id of the way or the exact street name (that I will have from the external geocoder).

**Comment by ericrwolfe** [comment]
@gardster great example. Addresses near tunnels and bridges are a huge problem right now.

**Pull request closed without merging**
