### PR TITLE
Implement usage of abstract interfaces in all routing algorithms

### PR DESCRIPTION
**Pull request by deniskoronchik**
# Issue

Use abstract interfaces in algorithms: #4158 

## Tasklist
 - [ ] review
 - [ ] adjust for comments

## Requirements / Relations
 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by TheMarex** [comment]
Thanks for this. However we have consciously avoided passing the base-class everywhere because we think we don't need run-time polymorphism.

I implemented a compile-time approach in https://github.com/Project-OSRM/osrm-backend/pull/4291 I hope this unblocks you.

**Comment by vng** [comment]
Well, #4291 looks good if we will have an opportunity to override some specific behavior in DataFacade<SomeOfflineMLD> data storage. And hope that it will be possible to override any specific algorithm components, leaving the main algorithm functions as-is.

**Comment by vng** [comment]
UPD: I didn't realize where "DataFacade" comes from ... Is it the replacement of ``` template <AlgorithmT> class AlgorithmDataFacade ``` ?

**Comment by deniskoronchik** [comment]
Will prepare new approach pull request

**Pull request closed without merging**
